import type { AuthoredDay } from './types';
import { sources as s } from './sources';

export const day14: AuthoredDay = {
  reviewedAt: '2026-09-10', revision: '逐课编写 1.0',
  deliverable: '一张训练 step 临界路径图、一个能分开测量 DataLoader 等待与计算窗口的 PyTorch 脚本，以及一份针对 RAW/SO-101 数据管线的优化优先级表。',
  question: {
    title: 'GPU 利用率只有 35%，把 num_workers 从 0 加到 8 就一定能提速吗？怎样用证据决定？',
    summary: '先分段测量稳定窗口，再用参数扫描和正确性门禁判断瓶颈。',
    keywords: ['DataLoader', 'GPU 利用率', 'data_wait', '临界路径', '同步', '正确性'],
    reference: '不能只凭 GPU 利用率调 worker。先在经过 warmup 的固定 step 窗口内分别测 next(loader_iter) 的等待、H2D、前向/反向/optimizer 和显式同步后的墙钟时间，并用 profiler 的 record_function 标签核对调用栈；再在相同 batch、数据顺序和增强语义下扫描 num_workers、prefetch_factor、persistent_workers 与 pin_memory。若 data_wait 位于临界路径且随 worker 增加下降，吞吐才可能提高；若计算、同步、磁盘、解码或主机内存已是瓶颈，盲目加 worker 可能只增加进程复制、排队和抖动。',
  },
  lessons: {
    foundation: {
      title: 'Profiler 与数据加载瓶颈：先画出一个 step 的临界路径', minutes: 32,
      prerequisites: '已完成训练循环、AMP、loss 与 checkpoint 课程，能区分 batch、step、CPU/GPU 和墙钟时间。',
      connection: '昨天把训练状态固定为可续训 checkpoint；今天在同一配置与数据身份上测量时间，避免把不同实验的速度混为一谈。明天将进入 episode、frame 与 transition 的机器人数据工程。',
      intro: '性能分析不是寻找“最慢函数”的排行榜，而是回答哪一段正在阻塞下一次参数更新。异步 GPU、DataLoader 预取和 Python 调度会让直觉失真，因此先定义观测窗口、同步边界和正确性不变量。',
      outcomes: ['把一个训练 step 拆成等待、传输、计算与同步阶段', '解释 self time、total time 和墙钟时间为何回答不同问题', '用临界路径而非单一利用率判断数据加载瓶颈'],
      sections: [
        { heading: '01 吞吐问题先从时间轴而不是百分比开始', body: '一个训练循环表面上是“取 batch、搬到设备、前向、反向、更新”，真实执行却可能重叠：DataLoader worker 在准备下一批，CPU 发射 CUDA kernel 后立即返回，GPU 仍在计算。任务管理器里的某个利用率采样只是时间轴投影，无法说明空洞发生在解码、队列、传输还是同步。\n\n先用 record_function 给 data_wait、host_to_device、forward、backward 和 optimizer_step 标注，再同时保留端到端墙钟。标签帮助定位调用层级，墙钟决定用户真正等待多久；二者必须在相同 batch size、输入尺寸、AMP 与梯度累积配置下比较。', sourceIds: ['profilerRecipe'] },
        { heading: '02 稳态 step 是重叠管线的最大项加缝隙', body: '若第 n 批计算与第 n+1 批准备充分重叠，稳态 step 时间近似由数据路径与计算路径的较大者决定，再加无法重叠的队列空洞和同步成本。若数据准备 70 ms、计算 40 ms，单纯让计算快 10 ms 几乎不改变 70 ms 的临界路径。\n\n这个近似只适合稳定流水线，首批 worker 启动、文件缓存预热、编译和最后排空应单列。吞吐 Q=B/T_step，其中 B 是每次参数更新的有效样本数；若有梯度累积，不能把 microbatch 数和 optimizer step 数混用。', formulas: [{ latex: 'T_{\\mathrm{step}}\\approx\\max(T_{\\mathrm{data}},T_{\\mathrm{compute}})+T_{\\mathrm{gap}}+T_{\\mathrm{sync}},\\qquad Q=\\frac{B}{T_{\\mathrm{step}}}', explanation: 'T_data 是下一批可用前的数据路径时间，T_compute 是当前批计算路径，T_gap 是未被重叠覆盖的调度空洞，T_sync 是为获得正确边界而付出的同步；B 是每次更新的有效样本数。' }] },
        { heading: '03 self time 与 total time 不要混着解释', body: 'Profiler 的 total CPU time 包含子调用，self CPU time 排除子调用。一个高层 train_step 的 total 很大很正常，它包住所有工作；若把它当成自身 Python 开销，就会重复计算。相反，底层 decode 的 self time 大，才说明时间真正留在该操作内部。\n\nGPU kernel 通常异步提交。只在 model(x) 前后用 perf_counter，测到的可能主要是 kernel 发射时间；为了得到该段 GPU 墙钟，需要在边界同步或使用 CUDA event。同步会扰动重叠，所以短诊断窗口与长期吞吐窗口应分开，不能把“为了测量而制造的等待”误判成生产瓶颈。', sourceIds: ['profilerRecipe'] },
        { heading: '04 DataLoader 参数会改变资源拓扑', body: 'num_workers=0 时，取样与变换在主进程执行，容易直接阻塞计算；大于 0 时启用多进程，但 worker 会接触并可能复制父进程中的 Python 对象，内存占用可随 worker 数增长。prefetch_factor 表示每个 worker 预取的 batch 数，persistent_workers 可避免每个 epoch 反复启动 worker，但都会增加常驻资源。\n\n在 macOS 上 multiprocessing 默认采用 spawn，脚本入口要放在 if __name__ == \"__main__\" 下，自定义 Dataset/collate_fn 需是模块顶层定义。worker 内直接返回 CUDA tensor 通常不推荐；先验证 pinned memory 与 non_blocking 传输是否真的处于可重叠路径。', sourceIds: ['dataLoaderDocs', 'dataWorkerSource', 'pinMemoryGuide'] },
      ],
      points: ['墙钟吞吐是结果，Profiler 标签和调用表用于解释结果。', '异步执行要求明确同步边界；诊断同步不应永久塞进生产循环。', 'worker、预取和 pinned memory 是待测变量，不是越大越快的旋钮。'],
      codeTitle: 'profiler_labels.py · 原创 CPU 标签与错误计时负例',
      code: ['import time', 'import torch', 'from torch.profiler import profile, record_function, ProfilerActivity', '', 'x = torch.randn(64, 32)', 'w = torch.randn(32, 16, requires_grad=True)', '', 'with profile(activities=[ProfilerActivity.CPU]) as prof:', '    with record_function("decode_batch"):', '        time.sleep(0.01)', '        batch = x.square()', '    with record_function("train_compute"):', '        loss = (batch @ w).square().mean()', '        loss.backward()', '', 'rows = {event.key: event for event in prof.key_averages()}', 'assert "decode_batch" in rows and "train_compute" in rows', 'assert rows["decode_batch"].cpu_time_total > 5_000', '', 'wrong_start = time.perf_counter()', '_ = batch', 'wrong_wait = time.perf_counter() - wrong_start', 'assert wrong_wait < 0.01', 'print("labels found; post-fetch timing misses wait: PASS")'].join('\n'),
      codeNotes: ['正例用 record_function 生成可搜索阶段名，并断言包含 sleep 的 decode_batch total CPU 时间超过 5 ms。', '负例在 batch 已经产生后才计时，只得到引用开销，演示“计时位置错误会漏掉等待”；真实 CUDA 区间还需同步或 event。'],
      exercise: { prompt: '为一个含 RAW 解码、颜色线性化、增强与 H2D 的 batch 画出两批重叠时间轴。', steps: ['标出主进程、worker 和 GPU 三条泳道。', '指出哪些区段可能重叠、哪些同步会切断重叠。', '写出一个不改变像素语义的正确性门禁。'], solution: 'worker 泳道包含读取、RAW 解包/去马赛克、线性化和增强，主进程包含队列等待、pin 与 H2D 发射，GPU 包含复制和训练 kernel。用 event/record_function 对齐边界，首批启动单列。优化前后对同一 frame ID 检查 shape、dtype、黑白电平/颜色变换配置、数值容差与增强种子，不能只比较吞吐。' },
      quiz: { question: '为什么在 model(batch) 前后调用 perf_counter 可能严重低估 GPU 计算时间？', hint: '考虑 CUDA kernel 的异步提交与主机返回时刻。', keywords: ['异步', 'CUDA', '同步', '墙钟', 'kernel 发射'], reference: 'CUDA 调用常把 kernel 排入队列后就把控制权还给 CPU，后一个 perf_counter 可能在 GPU 完成前执行，因此只覆盖发射开销。诊断局部 GPU 墙钟需在边界 synchronize 或用 CUDA event；但同步会改变流水线，应与无额外同步的长期吞吐测量分开。' },
      sources: [s.profilerRecipe, s.dataLoaderDocs, s.dataWorkerSource, s.pinMemoryGuide],
    },
    code: {
      title: '测量 GPU 利用率和 DataLoader 等待：构造可反驳的分段实验', minutes: 38,
      prerequisites: '能写 Dataset/DataLoader 与最小反向传播，并理解 perf_counter、warmup 和 profiler 标签。',
      connection: '基础课给出时间轴；本课用可运行的单进程受控实验验证计时边界，再把同一协议扩展到 GPU 与 worker 参数扫描。',
      intro: '脚本的目标不是伪造一个“GPU 利用率”，而是产生三份可交叉核对的证据：端到端 step、阻塞式 next 的 data_wait、以及训练计算时间。只有瓶颈定位和正确性检查同时成立，参数调整才算有效。',
      outcomes: ['正确测量 iterator 的阻塞等待而不是已取到 batch 的访问时间', '为 GPU 路径设置同步边界且保留 CPU 回退', '设计 num_workers/prefetch/persistent/pin 的小规模扫描表'],
      sections: [
        { heading: '01 计时器必须包住 next 调用', body: 'DataLoader 等待发生在 next(iterator) 内部：主进程可能等待 worker 队列，也可能在 num_workers=0 时亲自执行 Dataset.__getitem__ 和 collate。若先写 for batch in loader，再在循环体第一行开始计时，batch 已经到手，关键等待被 Python 迭代协议藏在计时器外。\n\n受控实验故意在 __getitem__ 中 sleep，令正确测量有可预测下界；错误测量在 next 返回后读取 batch，只会看到微小访问开销。这个负例验证测量协议本身，而不是拿人造 sleep 推断真实磁盘或解码速度。', sourceIds: ['dataLoaderSource'] },
        { heading: '02 端到端窗口与分段和不必严格相加', body: '每步记录 t0→next→同步计算→t1，可以得到 data_wait、compute 和 step_wall。CPU 串行示例中三者近似相加；真实多进程和 CUDA 管线中，下一批预取会与当前计算重叠，因此各阶段单独观察值的和可能大于端到端。\n\nGPU active ratio 可在一个同步后的长窗口内近似写成 kernel 活跃时间除以墙钟，但它不是驱动面板的统一定义。要记录使用了 profiler kernel 时间、CUDA event 还是采样工具；不同定义不能直接横向比较。', formulas: [{ latex: 'U_{\\mathrm{active}}=\\frac{T_{\\mathrm{kernel\\ active}}}{T_{\\mathrm{window}}},\\qquad 0\\le U_{\\mathrm{active}}\\le 1', explanation: 'T_kernel active 是定义清楚的测量窗口内 GPU kernel 实际活跃时长，T_window 是同一窗口墙钟；它是教学近似，不等同于所有监控面板的 GPU utilization 指标。' }] },
        { heading: '03 参数扫描一次只改变一个变量', body: '先固定数据 manifest、batch size、采样顺序、增强种子、模型与 step 数，丢弃 warmup 后测基线。接着逐个扫描 num_workers；当大于 0 时再比较 prefetch_factor，跨 epoch 任务再比较 persistent_workers，CUDA 传输路径最后比较 pin_memory/non_blocking。\n\n每个配置至少记录吞吐中位数与尾部等待，例如 data_wait p95，同时记录主机内存、错误数和 batch ID 哈希。平均吞吐提高但尾部卡顿恶化，可能让真机闭环产生控制空洞；SO-101 离线训练可接受的抖动，不应自动外推到在线推理。', sourceIds: ['dataLoaderDocs', 'dataWorkerSource'] },
        { heading: '04 多进程正例要尊重平台与数据语义', body: '文档要求 macOS/Windows 的主程序使用 main guard，worker 可访问的 Dataset、collate_fn 和 worker_init_fn 放在顶层。IterableDataset 会在每个 worker 拥有副本，需要用 get_worker_info 分片，否则样本可能重复；关闭 in_order 还可能影响复现并在不均衡数据上造成分布偏差。\n\n本课自动执行示例固定 num_workers=0，避免测试环境 spawn 与共享资源差异；真实实验应由独立脚本在目标机器上扫描。即便速度提升，也要比较 episode_id/frame_id 顺序、有效 mask、RAW 处理输出与 loss 首步，确认没有用重复、丢失或变义数据换吞吐。', sourceIds: ['dataLoaderDocs'] },
      ],
      points: ['把计时器放在 next 外侧，才能测到 DataLoader 阻塞。', '分段值因流水线重叠不一定可直接相加，端到端墙钟必须保留。', '性能实验同时记录吞吐、尾延迟、资源和数据语义。'],
      codeTitle: 'loader_wait_probe.py · 原创 DataLoader 等待正反例',
      code: ['import time', 'import torch', 'from torch.utils.data import Dataset, DataLoader', '', 'class SlowFrames(Dataset):', '    def __len__(self): return 8', '    def __getitem__(self, index):', '        time.sleep(0.01)', '        return torch.full((16,), float(index)), index', '', 'loader = DataLoader(SlowFrames(), batch_size=2, num_workers=0)', 'iterator = iter(loader)', 'records = []', 'model = torch.nn.Linear(16, 1)', '', 'for _ in range(3):', '    t0 = time.perf_counter()', '    batch, frame_ids = next(iterator)', '    t1 = time.perf_counter()', '    loss = model(batch).square().mean()', '    loss.backward(); model.zero_grad(set_to_none=True)', '    t2 = time.perf_counter()', '    records.append((t1 - t0, t2 - t1, t2 - t0, frame_ids.tolist()))', '', 'assert all(wait >= 0.015 for wait, _, _, _ in records)', 'assert [ids for *_, ids in records] == [[0, 1], [2, 3], [4, 5]]', 'already_ready = batch', 'bad_start = time.perf_counter()', '_ = already_ready.shape', 'wrong_wait = time.perf_counter() - bad_start', 'assert wrong_wait < min(row[0] for row in records)', 'print("3 waits measured; post-next negative test rejected: PASS")'].join('\n'),
      codeNotes: ['sleep 仅建立 num_workers=0 的可验证等待下界；正例还检查 frame ID 顺序，防止只测速度不测数据身份。', '脚本只运行 CPU、小张量和单进程，不写文件、不启动 worker、不访问 GPU 或机器人。真实 GPU 版本应在模型区间前后同步或用 event。', '负例在 next 已完成后测 shape 访问，显著小于真正等待，证明错误位置会漏掉瓶颈。'],
      exercise: { prompt: '把脚本扩展成 num_workers∈{0,2,4} 的独立扫描，并输出 CSV 风格结果。', steps: ['把执行入口放入 main guard，Dataset 保持顶层。', '每个配置新建 DataLoader、预热并测相同步数。', '记录吞吐、data_wait p50/p95、RSS 与 frame ID 哈希。'], solution: '为每个 worker 数单独构造 loader 与 iterator，首批和至少若干 warmup 不计；对采样数组排序取分位数，吞吐用有效样本/总墙钟。num_workers>0 时明确 prefetch_factor，跨 epoch 才比较 persistent_workers。所有配置先校验 frame ID 集合、次序契约与 batch 数，再按速度和内存共同选型。' },
      quiz: { question: '为什么 for batch in loader 循环体内的第一行计时不能代表 data_wait？', hint: 'Python 在进入循环体之前已经做了什么？', keywords: ['next', '迭代器', '计时边界', 'DataLoader', '阻塞'], reference: 'for 语句会先调用迭代器的 next，DataLoader 的排队等待、取样与组批都可能在这里发生；进入循环体时 batch 已返回。正确做法是显式创建 iterator，并让计时器包住 next(iterator)，同时保留端到端 step 与正确性记录。' },
      sources: [s.dataLoaderDocs, s.dataLoaderSource, s.dataWorkerSource, s.profilerRecipe],
    },
    insight: {
      title: '先优化哪里：用临界路径、Amdahl 与语义门禁缩短迭代周期', minutes: 27,
      prerequisites: '已经获得稳定窗口内的 data_wait、H2D、compute、同步与端到端吞吐，并能复现同一 checkpoint 和数据 manifest。',
      connection: '代码课给出测量表；路线课把它转成行动顺序，并为明天的 episode/frame/transition 数据工程保留身份与对齐约束。',
      intro: '个人项目最稀缺的不只是 GPU 秒数，而是从改动到可信结论的完整周转时间。优化应从最大可改进临界段开始，同时把实现成本、失败风险和数据语义回归纳入选择。',
      outcomes: ['用 Amdahl 上界识别收益很小的局部优化', '按收益、成本、风险排列 RAW/SO-101 优化实验', '把吞吐提升与数据等价、loss 等价和任务指标绑定'],
      sections: [
        { heading: '01 最大耗时不一定是最大可优化项', body: 'Profiler 表中最显眼的 total time 可能是包含子调用的外层，也可能是无法改变的固定成本。真正候选要同时满足：位于端到端临界路径、占比足够大、有可行优化手段，而且不会破坏数据或训练语义。\n\n例如 data_wait 占 40%，若通过缓存与并行最多提速 2 倍，整体上限只有 1.25 倍；即使把其余 60% 完全不动，这个上限也不会因局部 benchmark 更漂亮而改变。先算上界能避免花两天打磨只影响 3% 总时间的函数。', formulas: [{ latex: 'S_{\\mathrm{total}}=\\frac{1}{(1-p)+\\frac{p}{s}},\\qquad p=0.4,\\ s=2\\Rightarrow S_{\\mathrm{total}}=1.25', explanation: 'p 是端到端时间中可被目标优化覆盖的比例，s 是该部分局部加速倍数；示例说明局部翻倍只带来总体 25% 理论提升。' }] },
        { heading: '02 个人 VLA 项目按周转时间而非峰值吞吐排序', body: '一次实验的周转时间还包括数据准备、训练、评测、失败重跑与人工分析。将 JPEG 解码缓存后训练快 15%，但缓存生成要数小时且每次 RAW 参数变更都失效，短实验未必划算；相反，修复每 epoch 重启 worker 的空洞可能成本很低。\n\n可以给候选行动记录预期节省分钟、实现时长、额外内存、正确性风险与可回滚性。先做低风险观测与配置修复，再做缓存格式或数据流水线重写；云端 4090/5090 与本地 Mac 要分别测，不能把不同存储和进程模型的结论混成一个配置。', sourceIds: ['dataLoaderDocs'] },
        { heading: '03 RAW 管线的快不能以变义为代价', body: 'RAW 数据路径可能包含解包、黑电平、坏点、去马赛克、白平衡、颜色矩阵、裁剪与增强。把这些步骤缓存、融合或搬到 GPU 前，先声明输出究竟是线性 sensor space、相机 RGB 还是显示域；同一个 shape 和 dtype 并不代表相同光度语义。\n\n性能回归之外还需固定 frame ID 做像素统计/容差、饱和区域、颜色变换配置与下游首步 loss 对比。若优化改变增强随机数消耗或 episode/frame 对齐，即便吞吐提升也必须视为新数据版本，不能继续沿用旧 checkpoint 结论。', sourceIds: ['profilerRecipe'] },
        { heading: '04 从测量到行动采用一轮一假设', body: '每轮写出“若 data_wait 是瓶颈，则增加 2 workers 会降低 p95 等待且不改变 frame 哈希”这样的可反驳假设；只改一个变量，保留基线与失败日志。若等待下降而 step 不变，说明临界路径已转移到 compute/H2D，应停止继续加 worker。\n\n最终报告同时列速度、内存、稳定性与语义门禁：例如 samples/s、step p95、RSS、错误率、batch ID 哈希和验证指标。这个结构也能回答工程面试中的“先优化哪里”：不是背 num_workers=CPU 核数，而是展示定位、实验、反例、回滚与边界。', sourceIds: ['profilerRecipe', 'pinMemoryGuide'] },
      ],
      points: ['先算端到端收益上界，再比较实现成本和风险。', '本地 Mac 与云端 GPU 的数据路径不同，应分别测量并保留配置。', '速度结论只有通过数据身份、数值和任务指标门禁才有效。'],
      codeTitle: 'rank_bottlenecks.py · 原创 Amdahl 行动排序与语义负例',
      code: ['def project(name, fraction, local_speedup, hours, semantic_ok=True):', '    total_speedup = 1.0 / ((1.0 - fraction) + fraction / local_speedup)', '    score = (total_speedup - 1.0) / max(hours, 0.25)', '    return {"name": name, "speedup": total_speedup, "score": score, "safe": semantic_ok}', '', 'candidates = [', '    project("loader_workers", 0.40, 2.0, 1.0),', '    project("fused_raw_cache", 0.40, 3.0, 8.0, semantic_ok=False),', '    project("faster_logging", 0.05, 4.0, 0.5),', ']', 'allowed = [item for item in candidates if item["safe"]]', 'best = max(allowed, key=lambda item: item["score"])', 'assert best["name"] == "loader_workers"', 'assert abs(best["speedup"] - 1.25) < 1e-9', 'assert all(item["name"] != "fused_raw_cache" for item in allowed)', 'assert project("tiny", 0.03, 10.0, 1.0)["speedup"] < 1.03', 'print("Amdahl ranking passes; semantic-risk candidate rejected: PASS")'].join('\n'),
      codeNotes: ['score 只是教学用“总体收益/实现小时”代理，不包含内存、维护和不确定性；实际表格应显式保留这些列。', '正例选择总体上限 1.25× 且成本低的 loader 调整；负例把可能更快但尚未通过 RAW 语义门禁的缓存方案排除。'],
      exercise: { prompt: '用你自己的 profiler 数据填写一张三项优化决策表。', steps: ['为每项估计临界路径占比 p 与可实现局部倍数 s。', '记录工程时长、内存、回滚方式和数据语义门禁。', '先执行最高价值的低风险项并复测临界路径。'], solution: '表中至少包含基线窗口、p、s、Amdahl 总体上限、实现小时、RSS 增量、p95 风险、frame/episode 身份检查和首步 loss 容差。第一轮只改一个变量；若总体吞吐没有按预测变化，应更新时间轴而不是继续扩大参数。任何未通过数据语义或任务指标的方案不进入候选排名。' },
      quiz: { question: '一个函数占 step 时间 5%，即使把它加速 10 倍，为什么也不应优先于占 40% 且能加速 2 倍的数据路径？', hint: '分别代入 Amdahl 公式比较总体上限。', keywords: ['Amdahl', '占比', '局部加速', '总体吞吐', '临界路径'], reference: '5% 部分加速 10 倍的总体上限为 1/(0.95+0.05/10)，约 1.047 倍；40% 数据路径加速 2 倍的上限为 1/(0.6+0.4/2)=1.25 倍。还应比较实现成本与正确性风险，但只看局部倍数会错误排序。' },
      sources: [s.profilerRecipe, s.dataLoaderDocs, s.pinMemoryGuide],
    },
  },
};
