import type { AuthoredDay } from './types';
import { sources as s } from './sources';

export const day03: AuthoredDay = {
  reviewedAt: '2026-09-03', revision: '课程正文重写 2.0',
  deliverable: '手算一次 attention；完成 mask 泄漏反例；画出 SmolVLA 的条件 token 与动作 token 两条路径。',
  question: {
    title: '给 VLA 拼接图像、语言、关节和动作 token 后，为什么仍不能直接套用统一的下三角 mask？',
    summary: '分别说明 token 的语义、条件前缀的可见性、padding 的处理和动作生成方式。用一次被屏蔽 token 扰动测试证明你的 mask 有效。',
    keywords: ['前缀', 'padding', '因果', '动作', '位置', '泄漏'],
    reference: '拼接只统一宽度，不能自动确定信息访问关系。图像/语言/状态通常是已知条件，可能需要前缀内部双向交互；动作是自回归生成还是 flow 去噪决定其可见性，不能照搬语言模型 mask。padding 不是真实条件，应屏蔽对应 key；位置、相机和模态标识须按模型设计构造。固定合法 Q/K/V，仅扰动被屏蔽 token，合法 query 输出应保持不变；再移除 mask，结果应变化，形成负对照。',
  },
  lessons: {
    foundation: {
      title: 'Transformer 与多模态 Token：从一次加权求和理解 VLA 的上下文', minutes: 35,
      prerequisites: '会做矩阵乘法；知道 [B,N,d] 表示 batch、token 数和特征宽度。还不需要会训练大模型。',
      connection: '9 月 2 日把数据正确交给模型。今天解释模型内部怎样在图像、指令和关节信息之间选择相关内容；9 月 4 日再研究行动结果如何形成价值目标。',
      intro: '把图像和指令“拼起来”不是多模态理解。Transformer 的核心操作是：每个位置提出查询，与可见位置计算匹配分数，再读取它们携带的信息。本课先用只有两个 token 的数值例子算清楚，再扩展到机器人输入。',
      outcomes: ['写出 Q/K/V、attention 权重与输出的形状', '手算缩放、softmax 和 value 加权平均', '区分位置编码、模态投影和注意力 mask 的作用'],
      sections: [
        { heading: '01 Token 是向量，不等于自然语言中的一个字', body: 'token 可以是词片段、图像 patch 的特征，也可以是投影后的机器人关节状态。共同点是被表示成固定宽度向量，差异在于来源和语义。设特征宽度 d=256，某个图像 token 可能编码局部边缘和物体信息，某个状态 token 可能编码六个关节位置；维数相同并不意味着它们已天然对齐。\n\n举一个仅用于解释的输入：224×224 图像按 16×16 patch 划分，得到 14×14=196 个视觉 token；加 12 个文本 token 和 1 个状态 token，总共 209 个。两路相机则是 405 个。实际 VLA 可能使用视觉压缩或其他 patch 尺寸，不能把这个教学数量当成 SmolVLA 的真实配置。', formulas: [{ latex: 'N_{\\rm image}=\\frac{H}{P}\\frac{W}{P},\\qquad X\\in\\mathbb R^{B\\times N\\times d}', explanation: 'H、W 为图像高宽，P 为 patch 边长（此处假设整除）；B 为批量大小，N 为拼接后的 token 数，d 为统一隐藏宽度。' }] },
        { heading: '02 Q、K、V：找谁、如何被找到、交出什么信息', body: '同一个输入向量经过三组不同的线性投影，分别生成 Query、Key、Value。可以把 Query 理解为当前位置需要的信息类型，Key 是被查询位置用于匹配的索引，Value 是最终被读取的内容。这个类比帮助理解职责，但投影权重都是通过目标学习的，不是人工给每个维度贴上“颜色”“夹爪”等标签。\n\n自注意力的三者来自同一序列；交叉注意力的 Q 来自目标序列，K/V 来自另一组条件。比如动作 query 向视觉语言特征读取环境条件就是后者。无论哪种，匹配矩阵的行对应 query，列对应 key；很多 mask 写反的问题来自没有先写清这两个轴。', formulas: [{ latex: 'Q=XW_Q,\\quad K=XW_K,\\quad V=XW_V;\\qquad A=\\operatorname{softmax}_{\\rm key}\\left(\\frac{QK^\\top}{\\sqrt{d_k}}+M\\right),\\quad Y=AV', explanation: '对单个 head，Q 是 [Nq,dk]、K 是 [Nk,dk]、V 是 [Nk,dv]；A 是 [Nq,Nk]，Y 是 [Nq,dv]。softmax 沿 key 轴逐行归一化；M 为加性 mask。' }], sourceIds: ['attention'] },
        { heading: '03 两个 token 的完整手算', body: '取 q=(1,0)，两个 key 分别为 k₁=(1,0)、k₂=(0,1)，两个 value 为 v₁=(2,0)、v₂=(0,4)。点积得分是 (1,0)，因为 d_k=2，缩放后为 (0.7071,0)。指数归一化得到约 (0.6698,0.3302)；用未舍入的权重计算，输出约为 (1.3395,1.3210)。输出不是挑中某一个 token，而是读取内容的加权组合。\n\n为什么要除以平方根？在各维独立、零均值、单位方差的简化假设下，点积由 d_k 项乘积相加，方差随 d_k 增长。除以 √d_k 让尺度更稳定，避免 softmax 过早极度尖锐。这个推导依赖简化分布假设，不代表真实网络的每个维度永远独立。', formulas: [{ latex: '\\operatorname{Var}\\!\\left(\\sum_{i=1}^{d_k}q_i k_i\\right)=d_k,\\qquad \\alpha_1=\\frac{e^{1/\\sqrt2}}{e^{1/\\sqrt2}+1}\\approx0.6698', explanation: '方差公式用于说明尺度动机。上面的数值例子可以在本课代码中复核；若屏蔽第二个 key，输出应恰好变成 v₁。' }] },
        { heading: '04 位置与模态：宽度统一之后还缺什么', body: '纯 self-attention 没有内建“第几个位置”的概念。在没有位置编码且同步置换 token 的条件下，输出随输入一起置换；模型不能仅凭集合顺序知道哪一帧更早。因此需要位置机制。原 Transformer 使用正弦/余弦；后来模型还会采用可学习位置或旋转位置等方案。阅读具体仓库时应确认实际实现，而不是看到 Transformer 就假定用同一种位置编码。\n\n对机器人，序列位置还不够：同一个 patch 坐标在腕部相机和外部相机里代表不同视角；关节状态的量纲也不同于视觉特征。模态投影、相机标识、空间位置与时间信息各有职责。RAW 数据甚至不能直接套 RGB 的三通道归一化；这正是你传感器背景可以形成价值的地方。', formulas: [{ latex: '\\mathrm{PE}(p,2i)=\\sin\\!\\left(p/10000^{2i/d}\\right),\\qquad \\mathrm{PE}(p,2i+1)=\\cos\\!\\left(p/10000^{2i/d}\\right)', explanation: 'p 是位置，i 是一对正余弦通道的编号，d 是编码宽度。不同频率让同一位置拥有可区分的编码；这不是所有 VLA 都必须采用的公式。' }], sourceIds: ['attention'] },
        { heading: '05 Attention 只是一个模块，不是完整 Transformer', body: '多头注意力让模型在若干不同的投影子空间中计算关系，再将各 head 输出拼接并投影。之后的逐 token 前馈网络提供非线性特征变换；残差路径保留输入信息，归一化帮助稳定数值与训练。若只实现 QKᵀ、softmax、V 三步，你写的是 attention，不是完整 Transformer block。\n\n还要区分“上下文混合”与“动作输出”：attention 得到隐藏表示，动作头再把它映射成机器人动作或去噪向量场。语言模型能描述抓取，不等于动作坐标、执行频率与安全约束已经正确。我们明天会继续区分表示能力和行动价值，今天先把输入—隐藏表示—动作头这条链画准。', formulas: [{ latex: '\\mathrm{MHA}(X)=\\operatorname{Concat}(\\mathrm{head}_1,\\ldots,\\mathrm{head}_h)W_O', explanation: 'h 是 head 数；每个 head 有各自投影。标准多头设置常将 d 分为 h 份，实际实现还可能共享 K/V，需查配置。' }] },
        { heading: '06 Mask 控制信息边界，不能修复数据泄漏本身', body: 'padding mask 屏蔽为了组批而添加的空位；causal mask 限制看见未来位置；多模态前缀 mask 可以让已知条件内部互相可见，同时阻止条件读取尚未生成的动作。三者解决不同问题。并不是所有动作生成都要逐 token 自回归：生成整个带噪动作块的模型，合法注意力结构可能不同。\n\n即便 mask 正确，数据仍可能提前泄漏未来信息。例如把 t+1 的图像误当成 t 时刻输入，注意力无法知道时间戳标错了。基础课的数据语义与今天的网络信息边界是两道独立检查。正确做法是同时检查样本时间对齐，以及扰动被屏蔽 token 后合法输出是否不变。' },
      ],
      points: ['token 统一的是向量接口，不自动统一模态语义。', 'Q/K 决定读哪里，V 决定读到什么；用轴与数值例子验证理解。', '位置编码说明顺序，mask 限定可见性，数据时间戳说明物理时刻。'],
      codeTitle: 'attention_by_hand.py · 标准库即可运行的原创算例',
      code: ['from math import exp, sqrt', '', 'scores = [1 / sqrt(2), 0.0]', 'weights = [exp(x) / sum(exp(v) for v in scores) for x in scores]', 'values = [(2.0, 0.0), (0.0, 4.0)]', 'out = [sum(w * v[d] for w, v in zip(weights, values)) for d in range(2)]', 'assert abs(sum(weights) - 1.0) < 1e-12', 'assert abs(out[0] - 1.3395231) < 1e-5', 'assert abs(out[1] - 1.3209538) < 1e-5', 'print([round(x, 4) for x in weights], [round(x, 4) for x in out])'].join('\n'),
      codeNotes: ['这里的 softmax 只含两个较小得分；通用实现应先减最大值以避免指数溢出。', '这里没有训练 Q/K/V，也没有机器人输入，目的是核对线性代数，不是一个可部署策略。'],
      exercise: { prompt: '将第二个 key 屏蔽，并解释输出变化；再把两个 key 交换但保留各自配对的 value。', steps: ['屏蔽相当于第二个加性得分为负无穷。', '手算剩余权重和输出。', '同时交换 key/value 后，不加位置编码的单个 query 输出应怎样变化？'], solution: '屏蔽后权重为 (1,0)，输出为 (2,0)。同步交换两个 key/value 只改变权重的排列，最终输出不变；这说明无位置机制时读取是对 key/value 集合的操作。' },
      quiz: { question: 'Q 为 [2,4,10,16]、K 为 [2,4,20,16]、V 为 [2,4,20,8]，注意力权重和输出 shape 是什么？softmax 应沿哪个轴？', hint: '前两维是 batch 和 head，最后两维才参与矩阵乘法。', keywords: ['10', '20', '8', 'key', 'softmax'], reference: 'QKᵀ 为 [2,4,10,20]，每个 query 在 20 个 key 上归一化，即最后一个轴。乘 V 后输出 [2,4,10,8]。这里缩放除以 √16=4，而不是 √10 或 √20。' },
      sources: [s.attention, s.sdpa],
    },
    code: {
      title: 'Attention mask 与位置编号：用扰动测试抓住“偷看”', minutes: 35,
      prerequisites: '已理解 attention 的 query/key 两个轴，以及 padding 与 causal mask 的区别。',
      connection: '把基础课的公式变成一个可检验的布尔矩阵，再对应 LeRobot 的真实函数；不是重复昨天的训练循环。',
      intro: 'mask bug 经常不报错：shape 可以广播、loss 还能下降，模型却读到了不该读的信息。我们用四个 token 构建一个可手工检查的前缀，再通过有意改变 padding 内容验证屏蔽是否有效。',
      outcomes: ['从访问规则构造 [B,Nq,Nk] mask', '解释 PyTorch 两套 attention API 的相反布尔语义', '定位 SmolVLA 的 prefix/suffix、二维 mask 和 position_ids'],
      sections: [
        { heading: '01 先写一张访问表，再写张量广播', body: '设序列顺序为 L（指令）、I（图像）、P（补齐）、A（动作 query）。L 和 I 都是已知条件，允许相互读取；P 不是事实，所有合法 query 都不能读取它；A 可以读取 L、I 和自己的当前输入，但条件不能反向读取 A。这是一个教学用前缀结构，不宣称等价于所有 SmolVLA 配置。\n\n我们只关心 L、I、A 三个合法 query 的输出。P 对应的整行若全为负无穷，某些手写 softmax 实现会产生 NaN；下面让 P 行临时看见合法条件，再显式清零其输出。这是一种教学中的数值保护，不能据此要求上游所有实现采用同样策略。', formulas: [{ latex: 'A_{\\rm allow}=\\begin{bmatrix}1&1&0&0\\\\1&1&0&0\\\\1&1&0&0\\\\1&1&0&1\\end{bmatrix}', explanation: '行是 query，列是 key；1 表示可见。第三行是数值安全占位，最后乘 query 有效位将其输出归零。' }] },
        { heading: '02 布尔 True 在不同接口里含义可能相反', body: '在 torch.nn.functional.scaled_dot_product_attention 中，布尔 True 表示允许参与注意力；MultiheadAttention 的布尔 attn_mask 和 key_padding_mask 中，True 则表示屏蔽。两个 API 都能接收布尔张量，直接搬运代码未必会产生类型错误，却会把访问关系翻转。\n\n本课只调用 SDPA，因此变量明确命名为 allowed。传入前扩为 [B,1,Nq,Nk]，让 head 维广播；不要把 [B,N] padding mask 不加分析地塞给需要二维访问关系的接口。还要显式设置 dropout_p=0.0：SDPA 是函数调用，不能假定外部 module.eval() 会替你把这个参数关闭。', sourceIds: ['sdpa', 'mha'] },
        { heading: '03 位置编号需要跳过补齐，但还要处理补齐本身', body: '当有效位是 [1,1,0,1]，累计求和减一得到 [0,1,1,2]：最后一个真实 token 的位置是 2，而不是包含补齐后的数组索引 3。这样不同 padding 长度不会无故移动真实 token 的相对位置。对于开头存在 padding 的情况，减一会产生 -1，教学实现用 clamp_min(0) 使占位编号安全。\n\n这个处理并不赋予 padding 语义，仍要用 mask 阻止读取它，并忽略其输出。位置编号不是时间戳，也不等同于 flow matching 的噪声时间 t。阅读 SmolVLA 时要分别找到 sequence position 和动作去噪时间的嵌入入口；名字都叫“位置/时间”并不代表可以互换。' },
        { heading: '04 沿官方实现找到对应位置，而不是编造源码', body: '本次核对的 LeRobot 中，modeling_smolvla.py 的 embed_prefix 处理视觉、语言等条件，embed_suffix 处理带噪动作和去噪时间，forward 合并有效位并构造 attention mask；sample_actions 则涉及条件缓存和动作采样。公共工具已位于 policies/common/vla_utils.py，可搜索 make_att_2d_masks。\n\n阅读公共函数时，重点是“累计分组”：每个 token 的组编号由标记累计得到，query 可以访问组编号不晚于自己的合法 key。它能表达因果、前缀与块内双向等结构。下方例子是独立编写的教学 mask，不是逐字复制或冒充上游完整实现。官方 main 会变动，复现时应记录 commit 再定位这些函数。', sourceIds: ['smolcode', 'maskcode'] },
        { heading: '05 用不变性测试证明屏蔽有效', body: '固定 Q/K/V，把 P 的 key 和 value 改成很大的数。若所有合法输出保持不变，说明被屏蔽信息不能进入这些 query 的加权和。只检查权重 shape 不足以证明这一点；测试数值依赖比测试类型更接近 bug 的实质。再把 allowed 全设为 True，合法输出应变化，证明测试确实能发现泄漏。\n\n还要增加反方向测试：改变 A 的输入不能影响 L、I 的输出，但可以影响 A 自己。真实多层网络应在正确的信息边界处做端到端检查，因为上游投影或错误拼接也可能先混入未来信息。今天的测试先固定一层 attention，将问题收敛到可以手算的最小单元。' },
      ],
      points: ['先写访问表，后写广播；标清 query 行和 key 列。', 'SDPA 的 True 是允许，MHA 的 True 是屏蔽。', '扰动不可见 token 后输出不变，比只检查 shape 更有力。'],
      codeTitle: 'mask_invariance.py · 原创 CPU / PyTorch 检查',
      code: ['import torch', 'from torch.nn.functional import scaled_dot_product_attention as sdpa', '', 'torch.manual_seed(3)', 'q, k, v = [torch.randn(1, 1, 4, 8) for _ in range(3)]', 'valid = torch.tensor([[True, True, False, True]])', 'groups = torch.tensor([[0, 0, 0, 1]])', 'allowed = (groups[:, :, None] >= groups[:, None, :]) & valid[:, None, :]', 'positions = (valid.long().cumsum(-1) - 1).clamp_min(0)', 'assert positions.tolist() == [[0, 1, 1, 2]]', '', 'def attend(keys, values, mask):', '    out = sdpa(q, keys, values, attn_mask=mask[:, None], dropout_p=0.0)', '    return out * valid[:, None, :, None]', '', 'base = attend(k, v, allowed)', 'changed_k, changed_v = k.clone(), v.clone()', 'changed_k[:, :, 2] = 1000', 'changed_v[:, :, 2] = 1000', 'safe = attend(changed_k, changed_v, allowed)', 'torch.testing.assert_close(base, safe)', 'assert base[:, :, 2].abs().sum().item() == 0', 'unmasked = torch.ones_like(allowed)', 'assert not torch.allclose(attend(k, v, unmasked), attend(changed_k, changed_v, unmasked))', 'print("padding invariance + negative control: PASS")'].join('\n'),
      codeNotes: ['groups[:, :, None] 是 query 组，groups[:, None, :] 是 key 组；比较方向不可颠倒。', '有效 key 的检查在最后一维；query 无效位在输出端清零。', '教学分组常量与上游累计 mask 的表达等价性只限于本例访问表，不能直接替换整个模型。', '测试运行不需要下载 SmolVLA 权重，不连接机械臂。'],
      exercise: { prompt: '将 A 的 key/value 改为 -500，验证 L 和 I 不变，但 A 可能改变。', steps: ['只比较前两个合法 query 的输出。', '把 mask 的行列比较方向写反，观察哪条断言失效。', '解释为什么改 padding 的 query 却比较其他输出，不足以检测 key 泄漏。'], solution: 'A 对 L/I 不可见，因此前两行不变；A 自己允许读取 A，因而可变化。注意力中一个 query 只决定自身如何取值，被读取的信息在 K/V，故关键负例应扰动被禁止的 K/V。' },
      quiz: { question: '同一个布尔 mask 在 MHA 正常，在 SDPA 却泄漏 padding。最可能的原因是什么？如何用测试排除猜测？', hint: '明确 True 的含义，并提出正、负两个对照。', keywords: ['True', '允许', '屏蔽', '扰动', '不变'], reference: '两个接口布尔语义相反。按访问规则构造 allowed，SDPA 直接使用，MHA 则需要 blocked=~allowed（同时核对形状）。改变 padding 的 K/V，合法输出应不变；移除 mask 后应出现变化，证明测试有检出能力。' },
      sources: [s.sdpa, s.mha, s.smolcode, s.maskcode],
    },
    insight: {
      title: '共享上下文，不共享全部计算：多模态融合如何影响控制', minutes: 25,
      prerequisites: '已理解 self-attention / cross-attention 和 token 数、隐藏宽度。',
      connection: '从今天的注意力机制推导可计算的融合代价，而不是列举模型名字；给后续 SmolVLA 和 π0 单元建立比较坐标。',
      intro: '图像、语言和关节都进入策略后，真正的架构决策是：在哪一层交互，谁读取谁，哪些特征可以复用？本课用 token 数与信息更新频率比较“全部拼接”与“动作 query 读取条件”两条路线，并给 RAW 模态实验设定证据边界。',
      outcomes: ['估算密集 self-attention 与 cross-attention 的分数矩阵规模', '区分模态对齐、条件缓存和控制新鲜度', '提出能区分感知收益与计算代价的模态消融'],
      sections: [
        { heading: '01 全部拼接很直观，但代价随长度增长', body: '把所有条件和动作 token 拼在一起，优点是每层都能建立丰富交互，概念接口统一；代价是密集 self-attention 的分数矩阵随总长度平方增长。注意这是注意力矩阵元素数，不是整个网络 FLOPs，也不必然等于实际显存：高效内核可以不显式存储完整矩阵，但仍需考虑计算和带宽。\n\n假设视觉语言条件 N=400、动作 query K=50，拼接长度为 450，每个 head 有 202500 个分数。若新增一台相机再贡献 200 个条件 token，总长度变成 650，分数增到 422500，约 2.09 倍。增加传感器带来的代价，不能只按输入图片数量线性估算。', formulas: [{ latex: 'S_{\\rm joint}=(N+K)^2,\\qquad \\frac{650^2}{450^2}\\approx2.09', explanation: 'S 只统计每 head 的 query-key 配对数；未包含投影、MLP、视觉编码、head 数和缓存成本。数字为教学设定。' }] },
        { heading: '02 动作 query 读取条件，分离两类交互', body: '交叉注意力让动作 query 从条件特征读取内容，分数矩阵为 K×N；动作之间的自注意力再处理时序耦合，矩阵为 K×K。N=400、K=50 时，两者合计 22500 个分数，比联合 attention 的局部分数矩阵更小。但条件骨干本身仍要计算，不能据此声称整个模型快了 9 倍。\n\nSmolVLA 的公开说明采用交错的 cross-attention 与 self-attention 作为动作专家设计之一。这里可借鉴的不是“这种结构总是最好”，而是将“理解条件”和“协调动作”两个需求拆开。是否适合你的项目，要继续看状态输入位置、模型宽度、训练数据及执行时延。', formulas: [{ latex: 'S_{\\rm action}=KN+K^2=50\\times400+50^2=22500', explanation: '这是动作侧两种注意力的矩阵规模估计；不包含条件骨干，也不是实际测速。' }], sourceIds: ['smolvla'] },
        { heading: '03 条件缓存何时有意义，何时会变成陈旧观测', body: '一轮 flow 去噪会多次更新动作，但输入图像和指令可保持不变。若模型信息结构允许，就能缓存这轮条件的 K/V，避免在每次去噪时重复处理相同前缀。LeRobot 的 sample_actions 路径展示了相关缓存组织方式；阅读时要看缓存的创建、复用和作用域，而不是仅搜索 use_cache=True。\n\n缓存并不意味着可以无限期复用视觉特征。机器人拿起物体后场景已经变了，旧图像描述的状态可能不再适用。你应把“同一观测下的多次去噪”与“新控制周期的观测更新”分开。缓存新鲜度是系统假设；如果为了速度把感知冻结太久，节省的计算可能换来更差的纠错能力。', sourceIds: ['smolcode'] },
        { heading: '04 多一种模态不一定增加有效信息', body: '新增深度或 RAW 的收益取决于它补充了什么不可替代的信息。深度可能帮助几何定位，RAW 可能保留受 ISP 压缩或处理影响的光度信息；但它们都需要校准、对齐与适当编码。把 RAW 当作颜色稍不同的 RGB 直接送进预训练视觉编码器，可能产生输入分布偏移。\n\n对你的 RAW 合作项目，先选择确实由曝光、动态范围或材质引发失败的场景，再固定动作头和训练预算比较 RGB、RAW 与 RGB+RAW。若同时更换编码器规模或增加训练时长，就难以归因于模态本身。还要测正常光照场景，防止只在特殊挑战集有效而损害基本能力。这是本课提出的实验方案，不是某个模型已经验证的结论。' },
        { heading: '05 把“看得更多”与“控制得更好”拆成三层证据', body: '第一层看输入与特征：确认 RAW/深度时间对齐、有效范围和遮挡情况。第二层看离线动作预测：固定 eval episode 比较不同模态的误差，并按场景分组。第三层看闭环：在相同任务和安全规则下测成功率、恢复行为以及端到端时延。三层都保存失败例，而不只挑成功视频。\n\n如果新模态让离线误差下降却让动作延迟超出预算，下一步可能是 token 压缩、条件缓存或更轻编码器，而不是继续增加模型宽度。反之，若算力便宜但特征与动作无关，应回到数据和模态假设。今日路线判断的重点，是用 attention 的结构把成本说清楚，用控制实验把收益说清楚。' },
      ],
      points: ['拼接统一接口，cross-attention 可以分离条件读取和动作协调。', '矩阵规模估计不是整机加速比；必须保留条件编码成本。', '模态创新要同时证明信息收益和闭环代价可接受。'],
      codeTitle: 'token_budget.py · 原创复杂度算例',
      code: ['def scores(n, k):', '    return {"joint": (n + k) ** 2, "action_cross_self": k*n + k*k}', '', 'base = scores(400, 50)', 'extra_camera = scores(600, 50)', 'assert base == {"joint": 202500, "action_cross_self": 22500}', 'print(round(extra_camera["joint"] / base["joint"], 2))  # 2.09', '# These are score counts per head, NOT measured FLOPs or speedups.'].join('\n'),
      codeNotes: ['N 增加会同时影响条件骨干和动作侧，脚本只展示其中可直接算出的矩阵大小。', '比较真实模型还必须控制 hidden size、head 数、层数、batch 和硬件。'],
      exercise: { prompt: '为 RGB / RGB+RAW 实验写一张四列对照表：固定项、变化项、预期收益、可能代价。', steps: ['固定动作头、训练步数、episode 切分和成功标准。', '列出 token 数、编码时延和归一化方案。', '分别定义特殊光照与正常场景的评测，不把所有任务混成一个均值。'], solution: '变化项应聚焦输入模态与必要的适配器；报告适配器参数与额外训练成本。收益需要来自特定失败模式的改善，代价至少包括 p95 延迟、标定/数据采集成本和正常场景回归。' },
      quiz: { question: '动作侧 attention 分数数量降低 9 倍，能否宣布 VLA 推理快 9 倍？还有哪些成本未计算？', hint: '区分一个模块的局部操作量与端到端时间。', keywords: ['骨干', '编码', 'MLP', '时延', '缓存'], reference: '不能。还包含视觉/语言编码、投影、MLP、去噪步数、访存、相机预处理和控制通信。应固定硬件与配置做端到端测量，同时报告缓存是否命中及新观测更新频率。' },
      sources: [s.smolvla, s.smolcode, s.attention],
    },
  },
};
