import type { AuthoredDay } from './types';
import { sources as s } from './sources';

export const day09: AuthoredDay = {
  reviewedAt: '2026-09-05', revision: '逐课编写 1.0',
  deliverable: '一张 Autograd 动态计算图、一个能暴露 detach/in-place/零梯度的诊断器，以及一份 VLA 微调梯度验收表。',
  question: {
    title: '损失数值在正常下降，为什么仍不能证明你想训练的 VLA 模块收到了正确梯度？请设计训练前验证。',
    summary: '需同时检查计算图连通性、叶子 .grad、梯度尺度与一个故意断图的负例。',
    keywords: ['autograd', '计算图', 'detach', '梯度', '叶子', '负例'],
    reference: '损失可能由仍在训练的 action head 降低，而预期微调的视觉骨干已被 detach、冻结错误或无意间放进 no_grad；也可能因 .grad 未清零而看到旧值。应用一个固定小 batch：先列出预期可训参数，核对 requires_grad 与 loss.grad_fn，单次 backward 后记录每组 grad 是 None、全零、有限且非零，再 optimizer.zero_grad(set_to_none=True) 后确认回到 None。正例必须让目标模块有可手算的非零梯度；负例显式 detach 同一中间张量，验收器必须拒绝。最后再用有限差分或 gradcheck 核对小函数，但数值梯度通过也不代替参数分组和数据语义检查。',
  },
  lessons: {
    foundation: {
      title: 'Autograd 与动态计算图：从链式法则到叶子梯度累加', minutes: 32,
      prerequisites: '已完成 9 月 8 日的张量契约，会计算标量函数的导数，并能区分参数、输入与 loss。',
      connection: '昨天确保进入 forward 的张量含义正确；今天追踪 loss 如何把信号传回参数。明天才能有依据谈 optimizer、学习率和 warmup。',
      intro: 'Autograd 不是“帮你求一个导数”的黑箱：它在实际 forward 中记录运算关系，从输出接收向量后反向执行向量—雅可比积，最后把结果累加到叶子参数。',
      outcomes: ['手算一条分叉计算图的反向梯度', '解释 grad_fn、叶子与 .grad 的分工', '区分 backward、autograd.grad 和梯度累加'],
      sections: [
        { heading: '01 动态图记录这一次真正执行的路径', body: 'PyTorch 在默认 grad mode 中执行算子时，只要至少一个输入 requires_grad=True，结果就会持有 grad_fn，并与上游 Function 节点连成 DAG。Python if 选中哪个分支，本轮就记录哪条路；下一轮重新建图，不需要先画一张固定图。\n\n动态并不意味着一切路径都安全。根据 batch 内容跳过某个 VLA 分支时，那组参数本轮可能 grad=None；这可以是预期稀疏路由，也可能是数据键或条件写错。所以诊断要同时保存路由条件与参数梯度状态，不能只看总 loss。', sourceIds: ['autogradTutorial'] },
        { heading: '02 反向模式高效计算向量—雅可比积', body: '设向量 y=f(x)，完整 Jacobian J 的第 i,j 项是输出 y_i 对输入 x_j 的导数。训练通常从标量 loss 出发，不需显式存整个 J；backward 传入上游向量 v，沿图反向得到 v^T J。标量 loss 的默认 v=1，因此 loss.backward() 不需参数。\n\n数值例：x=2，a=x^2=4，b=3x=6，L=a+b=10。分支 a 贡献 2x=4，分支 b 贡献 3，在 x 汇合后得 dL/dx=7。这个“多条下游路径的梯度相加”正是多 loss、多模态或 residual 网络中必须核对的信号汇合。', formulas: [{ latex: 'J_{ij}=\\frac{\\partial y_i}{\\partial x_j},\\qquad \\bar{x}=v^{\\top}J', explanation: 'J 是 y 对 x 的 Jacobian，v 是从下游传来的向量，bar{x} 是反向模式返回的向量—雅可比积。' }], sourceIds: ['autogradTutorial'] },
        { heading: '03 叶子存 .grad，非叶子用 grad_fn 传递信号', body: '用户创建的 requires_grad=True 张量或 nn.Parameter 通常是叶子，grad_fn 为 None；算子结果是非叶子，其 grad_fn 记住如何向前传。backward 默认只把梯度落到需梯度的叶子 .grad，中间张量想保留 .grad 要显式 retain_grad()。\n\n因此“activation.grad 是 None”不能直接判断断图，要先问 activation 是否为叶子、是否调用 retain_grad。相反，预期可训参数在本轮确实参与 loss 后仍 grad=None，才是强烈断图信号。先分清对象身份，再解读 None。', sourceIds: ['autogradMechanics'] },
        { heading: '04 backward 会累加，清梯度是训练循环契约', body: '同一叶子参数上连续两次对新图 backward，第二次结果会加到旧 .grad，不会自动覆盖。这使梯度累积成为可用功能，也使遗漏 zero_grad 变成隐蔽 bug。set_to_none=True 会把未写入与真实零梯度分开，更利于诊断。\n\nautograd.grad 把指定输入的梯度作为返回值，适合函数式检查；backward 通常把结果累加到叶子 .grad，方便 optimizer 消费。两者都会在默认情况下释放已用图中间量；不应为了隐藏重复 backward 的结构错误而到处加 retain_graph=True。', sourceIds: ['autogradTutorial', 'autogradMechanics'] },
        { heading: '05 grad mode、no_grad、inference_mode 与 eval 是四件事', body: '默认 grad mode 才会根据 requires_grad 记图；no_grad 区域不记图，但其中创建的普通结果之后仍可在 grad mode 使用。inference_mode 还省掉视图跟踪和版本计数等开销，但里面创建的 inference tensor 与后续 autograd 交互有更强限制。\n\nmodel.eval() 只切换模块的 training 标志，影响 Dropout、BatchNorm 等定义了训练/评估行为的层；它不会关闭 Autograd。做评估时通常需要同时 eval() 与 no_grad/inference_mode，但两者解决不同问题，不能互相代替。', sourceIds: ['autogradMechanics'] },
      ],
      points: ['Autograd 每次 forward 动态记录实际执行路径。', '标量 loss 的 backward 是从 1 出发的反向 VJP。', '叶子 .grad 累加；None、零和非零梯度含义不同。'],
      codeTitle: 'autograd_basics.py · 原创分支梯度与累加实验',
      code: ['import torch', '', 'x = torch.tensor(2.0, requires_grad=True)', 'a = x.square()', 'b = 3 * x', 'loss = a + b', 'assert loss.item() == 10.0', 'assert loss.grad_fn is not None and x.grad_fn is None', 'loss.backward()', 'assert x.grad.item() == 7.0', '', '# A fresh graph accumulates another gradient unless .grad is cleared.', '(x.square()).backward()', 'assert x.grad.item() == 11.0', 'x.grad = None', 'assert x.grad is None', '', 'vjp = torch.autograd.grad(x.square() + 3*x, x)[0]', 'assert vjp.item() == 7.0', 'print("branch gradient=7; accumulation and VJP checked")'].join('\n'),
      codeNotes: ['7=2x+3，是 x=2 时两条分支梯度的和；第二个 x² 图再贡献 4。', '每个表达式都创建新图；示例不使用 retain_graph=True。', '直接把 .grad 设为 None 用于展示，模型训练中通常由 optimizer.zero_grad(set_to_none=True) 管理。'],
      exercise: { prompt: '把 L=x²+3x 改成 L=(x²)(3x)，先手算 x=2 时的梯度，再用 Autograd 验证。', steps: ['分别用乘积法则和化简后的 3x³ 求导。', '清空 x.grad 后在新图上 backward。', '检查数值与手算结果一致。'], solution: 'L=3x³，dL/dx=9x²，x=2 时为 36。乘积法则给出 (2x)(3x)+x²·3=24+12=36。测试前将 x.grad=None，否则会与前次累加。' },
      quiz: { question: '为什么非叶子 activation.grad 是 None 不足以判定“梯度断了”？', hint: '先说默认保存规则，再说如何验证。', keywords: ['非叶子', 'retain_grad', 'grad_fn', '参数', 'None'], reference: '非叶子的任务是通过 grad_fn 传播梯度，PyTorch 默认不保留其 .grad，所以 None 可能完全正常。可检查 activation.grad_fn，临时调用 retain_grad()，并以预期参与 loss 的叶子参数是否得到有限梯度作为主证据。' },
      sources: [s.autogradTutorial, s.autogradMechanics],
    },
    code: {
      title: '定位 detach、in-place 与梯度中断：从 Python grad_fn 追到 Engine 调度', minutes: 36,
      prerequisites: '能读 nn.Parameter、loss.backward()、grad_fn 和简单链式法则，已知道 .grad 会累加。',
      connection: '基础课建立语义；本课把“不收敛”拆成可重现的图连通、保存张量版本和参数梯度三类检查。',
      intro: 'detach 可以无声地变成常量边，in-place 可以修改 backward 所需的旧值，错误冻结则让参数根本不入图。诊断要先构造能证伪假设的小例子，再看大模型日志。',
      outcomes: ['区分 grad=None、全零与非有限梯度', '构造 detach 和 in-place 的故意失败测试', '从 grad_fn.next_functions 对应到 Autograd Engine 节点执行'],
      sections: [
        { heading: '01 detach 返回共享存储但不追踪历史的张量', body: 'detach() 产生不需梯度的视图，从它继续计算的那条边不会把梯度传回原图。这对停梯度 target、固定 teacher 或日志很有用；但若在 vision features 进 action head 之前误用，头部仍能降低 loss，backbone 却永远不更新。\n\n因为 detach 与原张量共享存储，对其中一方原地修改还可能影响另一方的数值。需要一份独立可变数据时应明确 clone()；但 clone 本身又可以保留梯度连接，“clone 还是 detach”要由所需的计算图契约决定，不是性能偏好。', sourceIds: ['autogradMechanics'] },
        { heading: '02 in-place 的危险在于 backward 需要 forward 的旧值', body: '某些 backward 公式会保存 forward 输入或输出。如果之后用 add_、copy_ 等修改了该张量，反向时再读就不是原来的值。PyTorch 为张量维护版本计数；save_for_backward 保存时也记住版本，不一致时明确报错，避免静默使用错值。\n\n“没报错”也不是所有 in-place 都无害，只表明 Autograd 未发现其破坏当前反向所需数据。阅读错误时要找“哪个张量被某个 backward 保存”，再追最后一次带下划线的操作；不要盲目把所有张量 clone，那会掩盖所有权设计且增加内存。', sourceIds: ['autogradMechanics', 'autogradFunction'] },
        { heading: '03 先做参数清单，再做梯度统计', body: '微调前把 named_parameters() 分组，显式列出哪些预期训练、哪些预期冻结。单个固定 batch backward 后，对可训组记录 None 数、全零数、非有限数、L2 norm 和最大绝对值；对冻结组则确认 .grad 仍为 None。这将配置意图变成可测契约。\n\ngrad=None 表示本轮没有梯度被写入；零张量表示路径可达但局部导数可能为零；NaN/Inf 表示数值已坏。三者对应的排查方向不同：None 查路由/冻结/detach，全零查激活区域、mask 或 loss 权重，非有限查输入、算子和混合精度。', sourceIds: ['autogradMechanics'] },
        { heading: '04 grad_fn.next_functions 是 Python 窗口，Engine 按依赖就绪调度', body: '从 loss.grad_fn 沿 next_functions 可以看到上游 Node 和 AccumulateGrad 边，适合在小例子中确认某参数是否可达。它不是稳定的业务 API，不应用类名硬编码生产逻辑；诊断产物应以参数契约和梯度测试为主。\n\n上游 C++ engine.cpp 中，Engine::execute 建立 GraphTask，compute_dependencies 统计节点依赖，就绪的 NodeTask 进 ReadyQueue，evaluate_function 执行节点并将输出梯度累入下一个节点的 InputBuffer。读源码是为了建立调度心智模型，不是在 Python 训练中复制一遍 Engine。', sourceIds: ['autogradEngine'] },
        { heading: '05 负例要证明诊断器会失败，不只是模型会跑', body: '下面小脚本保留一条 0*w 路，使 detach 负例的 loss 仍可 backward，但 w.grad 为全零；这比直接让 backward 报“loss 不需梯度”更像头部仍在学、骨干已断的真实情况。另一负例在平方 backward 保存中间量后原地修改，必须触发版本错误。\n\n测试不依赖 GPU、不下载权重，也不触碰机械臂。它的简化范围是标量参数和人工数据；真实 VLA 需将同样契约扩展到模块组、分布式参数、混合精度缩放前后和条件路由，但不应改变正负例的因果结构。' },
      ],
      points: ['detach 可以静默断掉一条边，in-place 可以破坏 backward 需要的旧值。', 'None、全零和 NaN/Inf 是三种不同诊断状态。', '源码调度模型帮助解释节点执行，产品验收仍要靠参数契约与反向测试。'],
      codeTitle: 'gradient_break_audit.py · 原创 detach/in-place 正负测试',
      code: ['import torch', '', 'def gradient(use_detach):', '    w = torch.tensor(2.0, requires_grad=True)', '    x, target = torch.tensor(3.0), torch.tensor(5.0)', '    feature = w * x', '    used = feature.detach() if use_detach else feature', '    loss = (used - target).square() + 0.0 * w', '    loss.backward()', '    return w.grad', '', 'good = gradient(False)', 'broken = gradient(True)', 'assert good is not None and good.item() == 6.0', 'assert broken is not None and broken.item() == 0.0', '', 'x = torch.tensor(2.0, requires_grad=True)', 'saved = x * 2', 'loss = saved.square()', 'saved.add_(1)', 'try:', '    loss.backward()', 'except RuntimeError as err:', '    assert "modified by an inplace operation" in str(err)', 'else:', '    raise AssertionError("in-place negative test did not fail")', 'print("detach zero-gradient and in-place version error: PASS")'].join('\n'),
      codeNotes: ['正例 loss=(6-5)²，dloss/dw=2·(6-5)·3=6，可以手算核对。', '0.0*w 故意保留一条零导数路径，让 detach 负例表现为全零而非 backward 无法运行。', 'in-place 错误文字来自 PyTorch 公开行为；不验证内部节点类名。'],
      exercise: { prompt: '给 gradient 函数增加“参数被 requires_grad_(False) 冻结”负例，并与 detach 结果区分。', steps: ['在 forward 前冻结 w，保证 loss 仍通过一个可训 head 可 backward。', '断言冻结 w.grad 为 None，detach 原例为全零张量。', '在报告中分别标记 frozen 和 reachable-zero。'], solution: '可另建 head=torch.tensor(1., requires_grad=True)，w.requires_grad_(False)，loss=(head*(w*x)-target)**2。backward 后 head.grad 有值、w.grad is None。原 detach 用 0*w 保留可达零路，w.grad 是零张量；两者不应在诊断中合并。' },
      quiz: { question: '预期微调的 vision backbone 所有 .grad 都是 None，你会按什么顺序缩小原因？', hint: '从配置意图、图连通、路由和清梯度时机回答。', keywords: ['requires_grad', 'detach', 'no_grad', '路由', 'zero_grad'], reference: '先核对 named_parameters 中该组 requires_grad 和 optimizer 分组；在固定小 batch 上检查 backbone 输出的 grad_fn，搜索 detach/no_grad/inference_mode；确认条件路由本轮真的调用了 backbone 且 loss 依赖其输出；最后确保在观测 .grad 前没有 zero_grad。用正例和显式 detach 负例验证审计器。' },
      sources: [s.autogradMechanics, s.autogradEngine, s.autogradFunction],
    },
    insight: {
      title: '梯度故障为何伪装成数据问题：用可证伪验收保护 VLA 微调预算', minutes: 27,
      prerequisites: '已运行 detach/in-place 负例，能解释 grad=None、全零和非有限梯度。',
      connection: '代码课会找单个断点；路线课把它变成云训练、RAW 分支和 SO-101 项目都可复用的启动门禁。',
      intro: '数据异常和梯度异常都会呈现 loss 平台、波动或只有局部模块学会的表象。区别不靠猜：数据契约证明输入，梯度契约证明学习信号，两者都通过才值得付长训练的时间与显存。',
      outcomes: ['用最小 batch 分离数据与梯度故障', '为冻结/解冻写可核对的参数预算', '设计 RAW 分支和 SO-101 action head 的启动验收'],
      sections: [
        { heading: '01 loss 会降只证明某条路在改变', body: '一个冻结错误的多模态系统中，action head 可以适应固定特征并让训练 loss 下降，这不能证明 RAW encoder 或视觉骨干已更新。反过来，某组梯度很小也不能单独证明断图，因为归一化、饱和、loss 权重或任务本身都会改变尺度。\n\n应将验收单位改为“参数组×固定 batch×指定 loss 项”：例如 action loss 应对 action head 有非零梯度，RAW 对照分支开启后应对 RAW adapter 有可达梯度，反之关闭时应为 None。这种因果对照比“梯度均值看起来正常”更可审计。' },
        { heading: '02 用参数预算验证冻结策略', body: '设组 g 有 N_g 个参数，先计算预期可训数和实际 requires_grad=True 数，必须逐组相等。若规划只训 action head 与 adapter，骨干不应因模块命名变化而混入 optimizer；若计划解冻最后两层，也不能只用模糊子串匹配。\n\n训练步还要记录实际获得 grad 的参数数 M_g，定义覆盖率 C_g=M_g/N_g。这是工程审计量，不是模型质量分数；全参数微调中 C_g<1 通常需解释，而 MoE/条件路由中单个 batch 本来就可能小于 1，要与路由日志一起看。', formulas: [{ latex: 'C_g=\\frac{M_g}{N_g},\\qquad M_g=\\sum_{p\\in g}\\mathbf{1}[p.\\mathrm{grad}\\neq\\varnothing]', explanation: 'N_g 是组 g 中预期可训参数数，M_g 是本轮实际得到梯度的数量；C_g 只表示覆盖，不表示梯度正确或模型更好。' }] },
        { heading: '03 云训练前先买几秒证据，不要先买整晚算力', body: '在 CPU 或小 GPU 上用 1–2 个人工可解样本做 forward/backward，记录 loss 分项、参数清单、grad 状态与一次 optimizer step 后的参数差。目标不是估计最终成功率，而是证明预期模块能收到有限信号、冻结模块不会变、故意 detach 会被拒绝。\n\n收益是在数据加载、分布式和混合精度加入前先隔离 Autograd 问题；代价是需维护一份小 fixture 和参数分组清单。对个人云算力，这个代价通常远小于一次无效训练；但小 fixture 通过后仍须在真实 batch 复查尺度和数值稳定性。' },
        { heading: '04 RAW 模态要用消融和断图负例共同验收', body: '对 RGB+RAW 融合，先固定同一 episode split 和 action loss，再比较三个图：RGB-only 时 RAW adapter 不参与；RGB+RAW 时它应有非零梯度；RGB+RAW-detached 时诊断器应明确失败。如果三者梯度状态相同，先修图路由，不解读成“RAW 没价值”。\n\n正确梯度只证明系统能从该 loss 学，不证明 RAW 带来泛化。价值结论还需固定训练预算、带特定光照/高动态范围的评测网格、普通场景回归和多次重复。梯度验收是消融实验的入场券，不是实验结论。' },
        { heading: '05 SO-101 项目只验证离线梯度，不在自动化中发动机械臂', body: '个人项目可以从一个经授权的离线 batch 验证图路：图像和 state 经 encoder，action chunk 经 mask 后进 loss，期望 action head 与指定 adapter 有梯度。加入一个全 false valid mask 负例时，验收器应在 backward 前拒绝“有效元素为零”，不该把零梯度归因为模型。\n\n自动备课和测试不执行 send_action、标定或任何真机控制，也不上传客户数据。将来真机前还要单独通过限位、急停、速度和工作空间验收。这一日的产出是学习信号证据，不是安全部署许可。' },
      ],
      points: ['loss 下降不能证明每个目标模块都在学。', '参数预算和梯度覆盖率是调试证据，不是模型质量分。', 'RAW 消融先验连通性，再用真实场景评测价值；SO-101 梯度测试不授权真机执行。'],
      codeTitle: 'gradient_budget.py · 原创参数组覆盖验收',
      code: ['import torch', '', 'rgb = torch.tensor(2.0, requires_grad=True)', 'raw = torch.tensor(3.0, requires_grad=True)', 'head = torch.tensor(1.0, requires_grad=True)', '', 'def run(use_raw, detach_raw=False):', '    for p in (rgb, raw, head):', '        p.grad = None', '    raw_term = raw.detach() if detach_raw else raw', '    feature = rgb + (raw_term if use_raw else 0.0)', '    loss = (head * feature - 1.0).square()', '    loss.backward()', '    return [p.grad for p in (rgb, raw, head)]', '', 'rgb_only = run(False)', 'assert rgb_only[0] is not None and rgb_only[1] is None', 'fused = run(True)', 'assert all(g is not None and torch.isfinite(g) and g.abs() > 0 for g in fused)', 'broken = run(True, detach_raw=True)', 'assert broken[1] is None', 'coverage = sum(g is not None for g in fused) / len(fused)', 'assert coverage == 1.0', 'print("RGB/RAW routing gradients and coverage: PASS")'].join('\n'),
      codeNotes: ['三个标量只模拟 RGB adapter、RAW adapter 和 action head 三组，不代表真实 VLA 架构。', 'RGB-only 中 raw.grad=None 是预期路由；fused 中三组都必须有非零有限梯度。', 'detach_raw 负例专门要求 RAW 梯度缺失，实际验收应反过来将此状态判为失败。'],
      exercise: { prompt: '将梯度预算扩展为“冻结 RGB encoder，训练 RAW adapter 与 action head”配置。', steps: ['先写每组预期 requires_grad 和预期 .grad 状态。', '用一次 fused backward 检查 RGB 不变、RAW/head 有梯度。', '再加 RAW detach 负例，确认门禁拒绝。'], solution: '将 rgb.requires_grad_(False)，预期 rgb.grad is None；raw 和 head 保持 True，fused loss 后两者的 grad 应为有限且非零。将 raw_term 换成 raw.detach() 后 raw.grad 变 None，门禁必须失败，即使 head.grad 仍有值且 loss 可计算。' },
      quiz: { question: 'RGB+RAW 训练中 RAW adapter 的梯度审计通过，为什么还不能宣称 RAW 提升了真机表现？', hint: '区分可学习性证据与价值证据。', keywords: ['梯度', '消融', '评测', 'RAW', '泛化'], reference: '梯度通过只证明 action loss 能沿当前图更新 RAW adapter，不证明信号有用、时间对齐正确或真机泛化提升。还需固定 split、训练预算和其他模块的 RGB-only 对照，在预先定义的高动态范围与普通场景上重复评测，并报告失败与回归。' },
      sources: [s.autogradMechanics, s.autogradTutorial, s.autogradEngine],
    },
  },
};
