import type { AuthoredDay } from './types';
import { sources as s } from './sources';

export const day08: AuthoredDay = {
  reviewedAt: '2026-09-04', revision: '逐课编写 1.0',
  deliverable: '一张具名轴张量契约、一个可运行 batch 验证器，以及一份 SO-101 数据接口变更清单。',
  question: {
    title: '一个动作张量从 [B,K,A] 变成 [B,A,K] 后，元素总数、dtype 和 device 都没变。为什么这仍可能是灾难性错误？怎样在训练前抓住它？',
    summary: '回答必须区分机器可见属性与轴语义，并给出至少一个正例、一个故意失败测试。',
    keywords: ['轴', '语义', 'shape', '契约', '断言', '动作'],
    reference: 'numel、dtype、device 相同只证明存储规模与位置没变，不证明第二轴仍是时间、第三轴仍是动作。若下游按 [B,K,A] 解释 [B,A,K]，可能把关节维当时间切 chunk，且在 A=K 时连 shape 都完全相同。应在数据边界写具名契约：键名、轴顺序、各轴含义/允许范围、dtype、device、单位和归一化版本；用非对称测试尺寸（如 K=4、A=6）验证正例，交换轴必须抛错，并用带唯一数值模式的 fixture 检查索引语义，而不只比较 tuple。',
  },
  lessons: {
    foundation: {
      title: '张量不是一串数字：shape、dtype、device 与轴语义的完整契约', minutes: 30,
      prerequisites: '已能读 PyTorch 张量，并理解机器人 batch、动作块和多相机观测的基本形式。',
      connection: '第一周已经多次写出 [B,K,A]；今天把这些括号从注释升级为进入训练前可验证的接口。明天将继续追 autograd，错误契约必须先被隔离。',
      intro: '模型经常不是因为 Transformer 不够强而失败，而是把“合法张量”解释成了错误事实。本课把 shape、dtype、device 逐项拆开，再补上 PyTorch 无法自动知道的轴名、单位、时间和归一化版本。',
      outcomes: ['能为图像、状态和动作写出具名轴契约', '计算张量元素数与最低存储量', '解释广播成功为何仍可能产生语义错误'],
      sections: [
        { heading: '01 shape 只给长度，轴名必须由系统补上', body: 'PyTorch 的 shape 是各维长度组成的 tuple。例如动作块 [8,16,6] 可以表示 B=8、未来 K=16、动作维 A=6；但库本身只看到三个整数，不知道第 2 轴是时间还是关节。把它误转成 [8,6,16] 后，元素总数仍相同，很多 reshape 也能成功，物理含义却已改变。\n\n具名契约至少写 key、轴顺序、每轴意义与动态/固定范围。对 SO-101，action 还应写六个元素分别对应哪个关节、单位是角度还是归一化位置、它是 proposed 还是 executed。若 K 恰好也等于 6，交换时间轴和动作轴连 shape 断言都抓不到，因此测试 fixture 要让每个轴长度不同，并用数值模式核对索引。', formulas: [{ latex: 'X\\in\\mathbb{R}^{B\\times K\\times A},\\qquad X[b,k,a]=x_{bka}', explanation: 'X 是动作 batch；b、k、a 分别索引样本、未来时间步和动作量。公式给出 shape 与索引语义，但动作名称、单位和时间基准仍要写入契约。' }], sourceIds: ['tensors'] },
        { heading: '02 dtype 决定表示范围与算术，不只是占几字节', body: '相机从采集端常以 uint8 HWC 到达；进入策略前可能变成 float32 BCHW 并缩放到 [0,1]。如果先在 uint8 中做除法或差分，溢出、截断与隐式提升规则可能改变结果。关节索引适合整数，连续动作与归一化统计通常需要浮点；布尔 mask 应保持 bool，避免把 0.2 之类的权重误当真假。\n\nLeRobot 的 VanillaObservationProcessorStep 明确检查输入图像为 channel-last uint8，添加 batch 轴，再重排为 BCHW、转 float32 并除以 255。这里最值得学习的不是记住一次转换，而是转换前后各有可验证契约。RAW 可能是 10/12/16 bit 容器，不能因存成 uint16 就照搬 RGB 的 255 分母；有效位深、黑电平和归一化必须单独记录。', sourceIds: ['observationProcessor'] },
        { heading: '03 device 是数据所在位置，也是隐含的数据移动成本', body: '默认新张量通常在 CPU；参数可能在 CUDA、MPS 或其他加速器。算子要求参与运算的张量位于兼容设备，输入、target、mask 或新建常数漏搬一个都可能报错。更隐蔽的是训练循环频繁在 CPU 与加速器间复制，程序能跑，却把等待时间藏进每一步。\n\nTensor.to 返回转换后的张量；它不保证原对象原地改变。常见错误是只写 batch.to(device) 却继续使用旧 batch。non_blocking 也不是“写上就一定异步”：是否能重叠取决于源内存、目标设备和后续同步。今天先验证位置一致，性能结论必须留到真实测量，不能从参数名推断。', sourceIds: ['tensorTo', 'tensors'] },
        { heading: '04 存储账单能发现荒谬输入，但不能证明语义正确', body: '元素数是各轴长度的乘积，最低数据字节数再乘每元素字节数。B=4 的 float32 RGB 图像 [4,3,224,224] 有 602112 个元素，占 2408448 字节，约 2.30 MiB；这还不含梯度、激活、布局开销和多视角。若误把 224 当 batch，账单会立刻异常，是很好的入口检查。\n\n但 [B,K,A] 与 [B,A,K] 的元素数完全一样，所以内存账单只能抓一类错误。完整验收要组合：schema 检查键和轴，dtype/device 检查表示与位置，数值范围检查归一化，语义 fixture 检查索引对应事实。任何一项通过都不能替代其余三项。', formulas: [{ latex: 'N=\\prod_{i=1}^{d}n_i,\\qquad M_{\\min}=N\\cdot s_{\\rm dtype}', explanation: 'n_i 是第 i 轴长度，s_dtype 是每元素字节数；M_min 只算张量数据本体，不是训练显存总量。' }] },
        { heading: '05 广播规则是数值便利，不是领域正确性证明', body: 'PyTorch 从末尾维向前比较两个 shape：长度相同、其中一个为 1，或某侧缺少该维时可以广播。动作归一化中，[B,K,A] 减 [A] 正是想要的行为，因为最后一轴同为动作维。但 [B,K,A] 减 [K,1] 也能成功，它会按时间步减不同标量；若你原本想减每关节均值，这就是静默错误。\n\n因此不要把“没报 shape error”当成测试。先声明统计量应为 [A]，显式断言 stats.shape == (A,)，再运算。对 mask 也一样：[B,K,1] 广播到 A 通常合理，[B,1,A] 则是在所有时间步重复动作维 mask。广播是工具，契约决定哪一种重复有物理含义。', sourceIds: ['broadcasting'] },
      ],
      points: ['shape 的数字不携带轴名、单位和时间含义。', 'dtype/device 决定表示与执行位置，转换前后都要验证。', '广播成功和 numel 相等都不能证明机器人语义正确。'],
      codeTitle: 'tensor_contract_basics.py · 原创属性与广播正负例',
      code: ['import torch', '', 'actions = torch.arange(2*4*6, dtype=torch.float32).reshape(2, 4, 6)', 'mean_per_joint = torch.arange(6, dtype=torch.float32)', 'normalized = actions - mean_per_joint', 'assert normalized.shape == (2, 4, 6)', 'assert actions.numel() * actions.element_size() == 192', '', '# 合法但语义错误：按时间步减数值，而不是按关节减均值', 'wrong_stats = torch.arange(4, dtype=torch.float32).reshape(4, 1)', 'wrong = actions - wrong_stats', 'assert wrong.shape == actions.shape', 'assert not torch.equal(wrong, normalized)', '', 'transposed = actions.transpose(1, 2)', 'assert transposed.numel() == actions.numel()', 'assert transposed.shape == (2, 6, 4)', 'print("attributes checked; broadcast trap exposed")'].join('\n'),
      codeNotes: ['192 字节来自 2×4×6 个 float32，每个 4 字节；这里只计算数据本体。', 'wrong 运算故意成功，用来证明广播兼容不等于统计量语义正确。', '使用 K=4、A=6 的非对称尺寸，避免轴交换后 shape 偶然相同。'],
      exercise: { prompt: '为图像 [B,C,H,W]、状态 [B,Q]、动作 [B,K,A] 写一张契约表，并加入 RAW 输入。', steps: ['写每个轴名、dtype、device 与数值范围。', '为 RAW 记录有效位深、黑电平和归一化版本。', '设计一个长度相同但轴顺序错误的负例。'], solution: '合格表应将 RGB 的 uint8 HWC 输入与 float32 BCHW 模型输入分开；状态/动作写单位、元素顺序和统计版本；RAW 不默认除 255。负例可把 K/A 交换并要求验证器拒绝。' },
      quiz: { question: '[B,K,A] 动作减去 [K,1] 张量能够运行，为什么仍应拒绝把后者当作关节均值？', hint: '从末尾维广播规则和轴含义分别回答。', keywords: ['广播', '时间', '关节', 'shape', '语义'], reference: '[K,1] 的末尾 1 可扩到 A，K 与时间轴相等，所以数值运算合法；但它给每个时间步一个标量，而关节均值应沿最后 A 轴变化，契约应是 [A]。应在运算前断言统计量 shape 和版本。' },
      sources: [s.tensors, s.broadcasting, s.tensorTo, s.observationProcessor],
    },
    code: {
      title: '实现 batch 契约检查器：在 forward 前把三类静默错误变成明确失败', minutes: 35,
      prerequisites: '理解字典、tuple、torch.dtype/device，以及 [B,C,H,W]、[B,K,A] 的轴顺序。',
      connection: '基础课说明属性为何不够；本课把键、轴、dtype、device、范围和跨张量 batch 一致性写成可执行代码。',
      intro: '真实训练出错时，栈追踪常落在很深的 attention 或 loss。更便宜的做法是在 DataLoader 输出边界验证契约，并让错误消息直接说出哪个键、预期什么、实际是什么。',
      outcomes: ['编写可读的张量规格与跨字段检查', '用正例和三种负例证明验证器生效', '说明断言适用边界及生产异常策略'],
      sections: [
        { heading: '01 先验证局部属性，再验证跨字段关系', body: '局部检查回答某个张量是否存在、rank/固定轴是否正确、dtype 和 device 是否符合要求。跨字段检查回答图像、状态、动作是否属于同一个 batch，以及 action 与 valid 是否共享 B、K。只做局部检查会漏掉图像 B=8、动作 B=4 这类各自合法但无法配对的问题。\n\n规格中的 None 表示动态轴，例如 batch 大小；3、224、224 和动作维 6 是当前教学配置的固定约定。动态不等于不检查：所有键的第 0 轴必须相等，K 必须与 valid 的第 1 轴相等。实际项目若允许多分辨率，应将范围或可选集合写进契约，而不是删除验证。' },
        { heading: '02 错误消息是接口的一部分', body: '若只得到 RuntimeError: size mismatch，排障者还要猜是哪一个变换改变了轴。验证器应输出键名、属性名、expected 和 actual。数据流水线存在多个 processor 时，可在每个阶段之后记录摘要；LeRobot 的调试指南也提供 hooks、step_through 和 transform_features 检查来观察中间状态。\n\n日志不要打印客户图像或完整动作数据。通常记录 shape、dtype、device、有限值比例、范围摘要与数据版本即可；必要时使用经过授权的样本 ID。可观测性不应扩大数据使用范围，这条约束对合作 POC 尤其重要。', sourceIds: ['processorDebug'] },
        { heading: '03 shape 检查要故意使用能暴露错误的 fixture', body: '如果测试使用 K=A=6，那么 transpose(1,2) 后仍是 [B,6,6]，普通 shape 检查无法发现。采用 K=4、A=6 能先抓住轴交换；再把 action[b,k,a] 设成 100b+10k+a，可检查某个索引是否仍对应预期时间与关节。测试数据不是越像真实分布越好，而是要让目标错误显眼。\n\n正例只能证明一条合法路径没有被误拒绝；负例证明护栏真的工作。至少覆盖缺键、轴错误、dtype 错误、device 错误与 batch 不一致。下面代码在 CPU 上运行，并用 meta device 构造不执行数值算子的设备负例；它不会连接 CUDA、MPS 或任何机械臂。' },
        { heading: '04 不要在验证器里偷偷修数据', body: '检查器发现 HWC 时若自动 permute，或发现 float64 时自动 cast，调用者可能永远不知道上游契约已变化。更危险的是错误轴长度恰好相同，自动 reshape 会把语义错误包装成“修复成功”。边界验证器应默认失败；转换由命名明确的 processor 执行，并在转换后再次验证。\n\n确有兼容需求时，把迁移写成有版本的适配器，例如 raw_v1_hwc_uint8 -> policy_v2_bchw_float32，记录输入/输出规格和测试。这样模型 checkpoint、归一化统计与数据版本可以共同指向一个接口版本，回放旧实验时不会依赖隐式猜测。' },
        { heading: '05 assert 适合教学测试，服务边界应用显式异常', body: 'Python 在优化模式下可能关闭 assert，因此生产数据入口不应只靠 assert 拒绝坏输入。教学脚本为了短小使用自定义 require 并抛 ValueError；错误会一直存在。单元测试可以用 assert 核对“本该抛出的异常确实抛了”。\n\n验证器也不是万能类型系统：它无法仅凭 [B,K,A] 判断关节名称是否排序正确，无法知道弧度是否误当角度，也无法确认 timestamp 来自哪个时钟。此类语义必须来自 metadata、版本和有已知答案的 fixture。目标不是写出一千条 if，而是在每个高代价边界放最小充分护栏。' },
      ],
      points: ['局部属性和跨张量关系需要分别验证。', '负例必须故意失败，错误消息要定位到具体键与属性。', '验证器负责拒绝；有版本的 processor 才负责转换。'],
      codeTitle: 'batch_contract.py · 原创 PyTorch 正负测试',
      code: ['import torch', '', 'def require(ok, message):', '    if not ok:', '        raise ValueError(message)', '', 'def validate(batch, device=torch.device("cpu")):', '    specs = {', '        "image": ((None, 3, 8, 8), torch.float32),', '        "state": ((None, 6), torch.float32),', '        "action": ((None, 4, 6), torch.float32),', '        "valid": ((None, 4), torch.bool),', '    }', '    for key, (shape, dtype) in specs.items():', '        require(key in batch, f"missing key: {key}")', '        x = batch[key]', '        require(x.ndim == len(shape), f"{key}.ndim expected {len(shape)}, got {x.ndim}")', '        require(all(e is None or a == e for a, e in zip(x.shape, shape)), f"{key}.shape expected {shape}, got {tuple(x.shape)}")', '        require(x.dtype == dtype, f"{key}.dtype expected {dtype}, got {x.dtype}")', '        require(x.device == device, f"{key}.device expected {device}, got {x.device}")', '    b = batch["image"].shape[0]', '    require(all(batch[k].shape[0] == b for k in specs), "batch axes disagree")', '    require(torch.isfinite(batch["image"]).all().item(), "image has non-finite values")', '    require(0 <= batch["image"].min().item() <= batch["image"].max().item() <= 1, "image outside [0,1]")', '    return True', '', 'good = {', '    "image": torch.zeros(2, 3, 8, 8),', '    "state": torch.zeros(2, 6),', '    "action": torch.zeros(2, 4, 6),', '    "valid": torch.ones(2, 4, dtype=torch.bool),', '}', 'assert validate(good)', '', 'bad_cases = []', 'bad_shape = dict(good, action=good["action"].transpose(1, 2))', 'bad_cases.append(bad_shape)', 'bad_dtype = dict(good, state=good["state"].double())', 'bad_cases.append(bad_dtype)', 'bad_batch = dict(good, valid=torch.ones(3, 4, dtype=torch.bool))', 'bad_cases.append(bad_batch)', 'for bad in bad_cases:', '    try:', '        validate(bad)', '    except ValueError:', '        pass', '    else:', '        raise AssertionError("negative contract test did not fail")', 'print("1 positive and 3 negative batch contracts: PASS")'].join('\n'),
      codeNotes: ['图像尺寸 8×8 是快速测试 fixture，不是 VLA 实际输入规格。', 'dict(good, ...) 只替换一个字段，保证每个负例只有一个主要变化。', '范围检查会同步读取标量；用于入口审计可以接受，热路径需评估开销或采样执行。'],
      exercise: { prompt: '增加两个负例：缺少 image 键，以及 image 中包含 NaN。', steps: ['每次仅修改一个因素。', '检查错误消息是否含 key 或 non-finite。', '确认 good 仍通过。'], solution: '可用 missing={k:v for k,v in good.items() if k!="image"}；NaN 负例先 clone image，再设置一个像素为 float("nan")。两者都应抛 ValueError，不能让测试只检查程序退出。' },
      quiz: { question: '为什么验证器不应在发现 HWC 图像后自动 permute 成 BCHW？', hint: '考虑上游回归、同长轴与实验可追溯性。', keywords: ['失败', '转换', '版本', '语义', '追溯'], reference: '自动修复会掩盖上游契约变化，且 H/W/C 长度偶然相同或轴语义错误时可能做出错误猜测。检查器应明确失败；转换放在具名、带版本且有正负测试的 processor 中，转换后再验证。' },
      sources: [s.tensors, s.observationProcessor, s.processorDebug],
    },
    insight: {
      title: '接口契约为何优先于堆模型：用可归因实验守住数据到策略的边界', minutes: 25,
      prerequisites: '已经运行 batch 验证器，能解释一个 shape 正确但语义错误的例子。',
      connection: '代码课建立局部护栏；路线课把护栏接到个人云算力、RAW 模态和 SO-101 迭代选择。',
      intro: '“接口契约优先”不是反对更大模型，而是给模型比较建立共同题面。若输入轴、单位或统计版本不断变化，参数量带来的差异会和数据错误混在一起，任何提升都无法归因。',
      outcomes: ['比较先扩模型与先固化接口的收益和代价', '估算多模态输入的最低字节与验证预算', '为 RGB/RAW/SO-101 设计版本化适配边界'],
      sections: [
        { heading: '01 更大模型不能修复一个定义错误的问题', body: '若 action 的关节顺序与驱动不一致，大模型可能在训练集上拟合错误顺序，真机仍执行错误关节；若归一化统计来自另一个数据版本，增加层数也不会恢复原坐标系。此时容量更大甚至更善于记住错误。先用小 batch 和契约测试证明任务定义一致，才值得讨论表达能力。\n\n收益是故障更早、实验可比较、复现成本更低；代价是需要维护 schema、适配器和测试，并在变化时显式迁移。这个成本不会消失，只是从“训练后猜原因”前移到“训练前说明变化”。对个人项目，前移通常更划算，因为一晚 4090 时间和周末真机窗口都有限。' },
        { heading: '02 多模态价值实验必须先统一可比边界', body: '比较 RGB 与 RGB+RAW 时，不能只说输入都叫 image。要固定 episode split、动作头、训练步数与评测协议，并分别记录两路的分辨率、位深、曝光时间、时间对齐和 encoder 输出规格。RAW encoder 可能改变 token 数、dtype 与延迟；这些都是实验变量，不应藏在预处理脚本。\n\n若 RGB 是 [B,3,H,W] float32，RAW 是 [B,1,H,W] uint16 容器，直接 cat 会触发 dtype 提升，却不代表黑电平、白平衡和动态范围已对齐。更安全的边界是各自 processor 输出具名、同 device 的特征，再由融合模块消费。RAW 是否有价值要由特定失败场景与正常场景的对照证明，不从位深直接推出成功率。' },
        { heading: '03 用账单判断先优化输入还是扩模型', body: '假设 B=4、RGB 224×224 float32，一路输入最低约 2.30 MiB；增加同尺寸单通道 float32 约 0.77 MiB。原始输入字节增长看似不大，但 encoder 激活、token 数和跨模态 attention 可能带来更大训练开销，所以不能只用文件大小估显存。先记录各边界的 shape/dtype/device 与阶段耗时，再决定压缩、冻结 encoder 或扩模型。\n\n若一个模型的参数量翻倍，却因为预处理 device 抖动让每步额外等待，硬件升级会掩盖问题而非解决。相反，若契约和 profile 都稳定，显存/算力确实被模型计算占满，再租更大 GPU 就有明确依据。路线选择应由可观测瓶颈触发，而不是默认“最新模型一定需要更贵机器”。', formulas: [{ latex: 'M_{\\rm input}=BHW\\left(C_{\\rm rgb}s_{\\rm rgb}+C_{\\rm raw}s_{\\rm raw}\\right)', explanation: '这是两种输入张量本体的最低字节；不含编码器激活、梯度、优化器和 attention 中间量，不能当训练显存预测。' }] },
        { heading: '04 版本化接口让合作数据与个人项目各守边界', body: '合作 POC 可共享的往往是字段定义、质量规则和匿名统计，而不是客户原始图像或内部代码。把契约文档与数据内容分离，可以在不上传数据的前提下复用工程方法：例如 timestamp 时钟域、action 来源、相机曝光单位、缺失值策略和 schema 版本。任何样本导出仍需授权。\n\nSO-101 个人项目可以采用同一套公开 schema 思路，但不要假定厂商 POC 的动作维与 SO-101 相同。为每个 embodiment 写 adapter，将设备关节名称/单位映射到 policy action；适配器有固定 fixture 和逆变换检查。这样成果展示的是“能建立可审计接口”，而不是泄露另一项目的数据。' },
        { heading: '05 何时允许契约变化，何时应停止实验', body: '契约并非永远冻结。新增相机、修改动作空间或升级归一化都可能合理，但必须提升版本、写迁移说明、更新 fixture，并重跑旧基线。若旧 checkpoint 无法明确解释新输入，应标为不兼容，而不是用默认值让它勉强运行。\n\n停止条件可以很具体：任何 batch key/轴/单位无来源说明，train/eval 使用不同统计，或转换后正负测试未通过，就不启动长训练；若只有可选元数据缺失且不影响本次模型输入，可记录限制后继续。接口门禁的目标是控制高代价风险，而非追求形式上的零警告。', formulas: [{ latex: 'E_{\\rm valid}=E_{\\rm run}\\,\\mathbf{1}[C_{\\rm data}=C_{\\rm model}=C_{\\rm eval}]', explanation: '这是决策规则而非统计定律：数据、模型和评测契约版本不一致时，本次运行不计为可比较实验。' }] },
      ],
      points: ['模型比较前先固定题面，否则提升无法归因。', 'RAW 的潜在价值需要版本化处理和场景对照，不由位深自动成立。', '契约可以变化，但变化必须显式版本化并重跑基线。'],
      codeTitle: 'contract_migration.py · 原创版本兼容性检查',
      code: ['contracts = {', '    "rgb_v1": {"axes": "BCHW", "dtype": "float32", "range": "0..1", "action": "so101_rad_v1"},', '    "raw_v1": {"axes": "B1HW", "dtype": "float32", "range": "black..white", "action": "so101_rad_v1"},', '}', '', 'def compatible(left, right):', '    return left["action"] == right["action"]', '', 'assert compatible(contracts["rgb_v1"], contracts["raw_v1"])', 'bad = dict(contracts["raw_v1"], action="other_robot_deg_v1")', 'assert not compatible(contracts["rgb_v1"], bad)', '', 'rgb_bytes = 4 * 3 * 224 * 224 * 4', 'raw_bytes = 4 * 1 * 224 * 224 * 4', 'assert (rgb_bytes, raw_bytes) == (2408448, 802816)', 'print("input bytes:", rgb_bytes + raw_bytes, "; activation memory not included")'].join('\n'),
      codeNotes: ['这个示例只比较动作契约是否能进入同一 policy，真实兼容检查还需键、shape、单位、统计和时间基准。', 'RAW 的 range 字符串是占位式 schema 描述；项目中要保存实际黑电平/白电平及版本。', '字节账单不创建大张量，也不代表训练显存。'],
      exercise: { prompt: '为一次“新增腕部相机”的接口升级写迁移清单。', steps: ['列出 schema 版本、旧 checkpoint 行为与默认值策略。', '写正例和缺相机负例。', '说明哪些旧基线需要重跑。'], solution: '应增加新视觉 key 与轴/dtype/range，明确旧模型是忽略该 key 还是不兼容；不得静默复制另一相机。processor 与模型各有 fixture，固定旧评测集重跑可比基线，并记录额外 token、时延和显存。' },
      quiz: { question: '什么时候“先扩模型”是合理选择，而不是继续完善接口？', hint: '给出已经通过的证据和真正的瓶颈。', keywords: ['契约', '基线', '瓶颈', '容量', '对照'], reference: '当数据/模型/评测契约版本一致，正负测试通过，固定小基线可复现，profile 与误差分析显示主要限制来自模型容量或表示能力，而不是数据错位、单位、device 搬运或评测变化时，才有可归因依据扩模型；扩展后仍应保持同一协议对照。' },
      sources: [s.observationProcessor, s.processorDebug, s.tensorTo, s.broadcasting],
    },
  },
};
