import type { AuthoredDay } from './types';
import { sources as s } from './sources';

export const day10: AuthoredDay = {
  reviewedAt: '2026-09-06', revision: '逐课编写 1.0',
  deliverable: '一张 AdamW 更新分解图、一个带 warmup/梯度裁剪/断言的训练步，以及一份 VLA 小预算调参卡。',
  question: {
    title: '同一批 VLA 数据上 loss 突然尖峰，你如何判断该改学习率、warmup 还是梯度裁剪，而不是同时乱调三项？',
    summary: '从更新尺度、尖峰发生时刻、裁剪触发率和固定对照实验给出可证伪诊断。',
    keywords: ['学习率', 'warmup', '梯度裁剪', '更新尺度', '对照', 'VLA'],
    reference: '先冻结数据顺序、模型初始化、有效 batch 与 loss 权重，记录每步学习率、裁剪前后总梯度范数、各参数组的参数范数和更新范数。若尖峰集中在训练最初且未达到目标学习率，比较有/无或更长 warmup；若任意阶段都由少量异常 batch 触发极大梯度，先查数据与 loss，再比较明确阈值的裁剪；若梯度正常但参数更新相对参数范数过大，则降低对应参数组学习率。每次只改变一个因素，用相同样本数而非仅相同 wall time 比较 loss、有限性、裁剪触发率与离线任务指标；裁剪或 warmup 只能作为护栏，不能掩盖 NaN、错 mask 或时间对齐错误。',
  },
  lessons: {
    foundation: {
      title: '优化器、学习率与 warmup：把梯度变成可解释的参数更新', minutes: 32,
      prerequisites: '已完成 9 月 9 日 Autograd，能区分 grad=None、零梯度与有限非零梯度，并会手算链式法则。',
      connection: '昨天证明目标参数收到梯度；今天决定如何消费梯度。明天将检查归一化、初始化与混合精度带来的数值稳定性。',
      intro: '优化器并不修正数据或梯度语义，它只根据当前梯度、历史状态和学习率生成更新。学习率、动量、weight decay 与 warmup 必须拆开理解，才能把训练故障变成可测假设。',
      outcomes: ['推导 SGD momentum 与 AdamW 的关键状态', '解释学习率和 decoupled weight decay 的不同作用', '用步数而非含糊 epoch 定义 warmup'],
      sections: [
        { heading: '01 从梯度到更新要先固定四个对象', body: '对参数 θ，Autograd 提供当前 batch 的梯度 g；优化器保存历史状态，例如动量或梯度平方均值；学习率 η 缩放本步更新；scheduler 只按既定规则改写 η。四者职责不同，loss 下降也不能反推某一项必然正确。\n\nPyTorch 的最小循环是清梯度、forward、计算 loss、backward、optimizer.step。zero_grad 应在下一次反向前执行，因为梯度默认累加；scheduler 若按每个 optimizer step 更新，则其计数单位必须与真正参数更新次数一致，不能把 micro-batch 次数误当更新步。', sourceIds: ['optimizationTutorial'] },
        { heading: '02 SGD momentum 与 Adam 的历史记忆不同', body: '普通 SGD 用 θ_t=θ_{t-1}-ηg_t；momentum 先把历史梯度指数汇入速度，再用速度更新。Adam 同时维护一阶矩 m_t 与二阶矩 v_t，经过偏差修正后，用 m̂_t/(√v̂_t+ε) 对不同参数方向自适应缩放。\n\n数值例取 β₁=0.9、β₂=0.999、第一步梯度 g₁=2、ε 可忽略，则 m₁=0.2、v₁=0.004；偏差修正得到 m̂₁=2、v̂₁=4，所以归一化方向约为 1，参数步长约为 η。此例只解释第一步尺度，不表示 Adam 以后忽略梯度大小。', formulas: [{ latex: 'm_t=\\beta_1m_{t-1}+(1-\\beta_1)g_t,\\quad v_t=\\beta_2v_{t-1}+(1-\\beta_2)g_t^2', explanation: 'm_t 与 v_t 分别是一阶、二阶指数移动平均；Adam 还会用 1-β₁^t 与 1-β₂^t 做早期偏差修正。' }], sourceIds: ['adamwDocs'] },
        { heading: '03 AdamW 将 weight decay 与 loss 梯度解耦', body: '在自适应优化器里，把 λθ 加进 loss 梯度后再经过 v_t 缩放，并不等同于直接让参数按比例衰减。AdamW 把 θ←(1-ηλ)θ 作为独立步骤，因此 decay 不累积进一阶和二阶矩；这正是论文与 PyTorch 文档强调的“decoupled”。\n\n参数组需要显式审计：预训练 backbone、新 action head、归一化参数和 bias 可以有不同学习率或 decay 规则，但“bias/Norm 永不衰减”不是数学定律。应保存每个 name 落入哪组、组内参数量和配置，避免字符串筛选悄悄漏参。', sourceIds: ['adamwPaper', 'adamwDocs', 'adamwSource'] },
        { heading: '04 warmup 是更新尺度的时间函数，不是神奇稳定器', body: 'warmup 在最初 W 个更新步把学习率从较小值升到目标值，之后再保持或衰减。Transformer 原论文使用 d_model^-0.5 乘上线性 warmup 与 inverse-square-root decay 的较小者，并设置 4000 步；这是一份具体机器翻译配方，不应直接复制成所有 VLA 的常数。\n\nPyTorch LinearLR 用乘法因子从 start_factor 线性走向 end_factor，total_iters 决定迭代数。这里的“迭代”由你调用 scheduler.step 的频率定义。若做 8 次梯度累积才 optimizer.step 一次，W=100 应解释为 100 次真实更新，而不是 100 个 micro-batch。', formulas: [{ latex: '\\eta_t=d^{-1/2}\\min(t^{-1/2},\\;tW^{-3/2})', explanation: 'η_t 是第 t 次参数更新的学习率，d 是模型宽度，W 是 warmup 步数；t≤W 时线性上升，之后按 t^-1/2 衰减。' }], sourceIds: ['transformerSchedule', 'linearLR'] },
        { heading: '05 看更新尺度而不只看 loss', body: '学习率乘在优化器给出的方向上，真正影响参数的是 Δθ。至少按参数组记录学习率、梯度范数、参数范数与更新后差值；若 backbone 的相对更新远大于新 head，可能破坏预训练表示，即使总 loss 在短期更快下降。\n\n优化器选择、base lr、warmup 和 decay 会互相作用，所以比较时每次只改一个因子，并固定 batch 顺序、有效 batch size、训练步数与评测集。一次小样本 loss 更低只是优化迹象，不是 VLA 真机成功率或泛化证据。', sourceIds: ['optimizationTutorial', 'adamwDocs'] },
      ],
      points: ['梯度、优化器状态、学习率和 scheduler 是四个不同对象。', 'AdamW 的 weight decay 不进入动量与方差。', 'warmup 按真实参数更新步计数，具体长度必须通过对照验证。'],
      codeTitle: 'adamw_first_step.py · 原创首步更新分解',
      code: ['import torch', '', 'theta = torch.nn.Parameter(torch.tensor(2.0))', 'opt = torch.optim.AdamW([theta], lr=0.1, betas=(0.9, 0.999), eps=1e-8, weight_decay=0.01)', 'loss = (theta - 1.0).square()', 'loss.backward()', 'assert theta.grad.item() == 2.0', 'before = theta.detach().clone()', 'opt.step()', '', '# First Adam direction is approximately +1; decoupled decay contributes lr*wd*theta.', 'expected = before * (1 - 0.1 * 0.01) - 0.1 * (2.0 / (4.0 ** 0.5 + 1e-8))', 'assert torch.allclose(theta.detach(), expected, atol=1e-6)', 'assert opt.state[theta]["step"].item() == 1', 'print("AdamW first step and decoupled decay: PASS")'].join('\n'),
      codeNotes: ['loss=(θ-1)²，在 θ=2 时梯度为 2；第一步偏差修正后的 Adam 方向近似 1。', 'expected 先做独立 decay，再做自适应梯度更新，和 PyTorch AdamW 公共公式一致。', '示例是单标量 CPU 教学模型，不代表 VLA 的推荐学习率或 decay。'],
      exercise: { prompt: '保持梯度不变，把 lr 从 0.1 改为 0.01，分别计算 decay 与 Adam 方向两项的变化。', steps: ['写出两种 lr 下的 (1-ηλ)θ。', '写出第一步约为 η 的自适应方向更新。', '核对总 Δθ 是否近似缩小十倍。'], solution: 'η=0.1 时 decay 量为 0.1·0.01·2=0.002，Adam 方向约 0.1，总更新约 0.102；η=0.01 时两项为 0.0002 与 0.01，总更新约 0.0102，均随 η 缩小十倍。' },
      quiz: { question: '为什么 AdamW 的 weight_decay 不能简单解释成“把 L2 项加进 loss”？', hint: '说明自适应缩放发生在什么位置。', keywords: ['AdamW', 'weight decay', 'L2', '解耦', '动量'], reference: 'Adam 中若把 λθ 加到梯度，它会进入一阶/二阶矩并被自适应分母缩放；AdamW 则直接对参数做 θ←(1-ηλ)θ，再执行梯度方向更新，decay 不进入动量或方差，因此两者通常不等价。' },
      sources: [s.optimizationTutorial, s.adamwDocs, s.adamwPaper, s.adamwSource, s.linearLR, s.transformerSchedule],
    },
    code: {
      title: '实现 scheduler 与梯度裁剪：顺序、单位和故意失败测试', minutes: 36,
      prerequisites: '理解 optimizer.step 消费叶子梯度，知道 AdamW 参数组和 warmup 的更新步语义。',
      connection: '基础课解释各组件；本课将它们写成带断言的训练步，为明天的 NaN/Inf 与混合精度排查保留证据。',
      intro: '可靠训练步要让每个动作可观察：裁剪前范数、裁剪后范数、当前学习率和调度计数都应能测试。下面用小模型验证正常路径，并让 NaN 梯度在更新前明确失败。',
      outcomes: ['按正确顺序组合 backward、clip、optimizer 与 scheduler', '解释 clip_grad_norm_ 的返回值和原地行为', '为 warmup 步数与非有限梯度写正负测试'],
      sections: [
        { heading: '01 裁剪的是所有参数梯度拼成的一个向量', body: 'clip_grad_norm_ 先把各参数梯度的范数合成总 p 范数；当总范数 G 超过阈值 C 时，所有梯度按同一比例缩放，使方向尽量保持而总范数不超过 C。函数原地修改 .grad，并返回裁剪前总范数，所以应在 optimizer.step 前调用。\n\n若每层各自裁剪，得到的是另一种算法，会改变层间比例。分布式或梯度累积中也要先明确你希望裁剪的是单 micro-batch、本地 shard，还是完整有效 batch 的同步梯度；教学脚本只覆盖单进程完整参数。', formulas: [{ latex: 'g\\leftarrow g\\cdot\\min\\left(1,\\frac{C}{\\lVert g\\rVert_p+\\varepsilon}\\right)', explanation: 'g 表示拼接后的全部梯度，C 是 max_norm；只有总范数超阈值时才整体缩小。' }], sourceIds: ['clipGrad'] },
        { heading: '02 训练步顺序决定你实际执行的算法', body: '一个更新步应先 zero_grad，再 forward/backward；混合精度时先 unscale；随后检查有限性并裁剪；再 optimizer.step，最后 scheduler.step。把裁剪放在 optimizer.step 后，只能修改已经被消费的旧梯度，无法撤回本次参数更新。\n\nPyTorch LinearLR 文档也要求 scheduler.step 在 optimizer.step 后。首次学习率如何初始化、调度器把第几次调用称为 last_epoch，必须用 get_last_lr 与断言核对；不要只凭代码位置猜曲线。', sourceIds: ['linearLR', 'clipGrad', 'optimizationTutorial'] },
        { heading: '03 warmup 的计数必须绑定成功更新', body: '如果梯度非有限、动态 loss scaling 跳过了 optimizer.step，或梯度累积尚未结束，这时是否推进 scheduler 会改变学习率与真实更新的对应关系。稳妥做法是只在参数实际更新后推进按 step 调度的 scheduler，并把 successful_update 作为日志字段。\n\n恢复训练还要同时加载 model、optimizer 与 scheduler state；只加载模型会丢失 AdamW 的 moment 和调度位置，表面上从旧参数继续，实际却以第一步状态和错误学习率重启。9 月 13 日会专门完成 checkpoint 与复现。', sourceIds: ['adamwDocs', 'linearLR'] },
        { heading: '04 非有限梯度应先失败，不能靠裁剪变正常', body: 'clip_grad_norm_ 的 error_if_nonfinite=True 会在总范数是 NaN/Inf 时抛错。NaN 乘任何裁剪系数仍是 NaN；把错误关闭或把梯度强制 nan_to_num 只会隐藏上游数据、loss、除零或混合精度问题。\n\n负测试要主动制造 NaN 梯度并断言门禁拒绝；正测试则制造已知大梯度，验证返回值大于阈值且原地裁剪后的范数不超阈值。只有同时具备正负例，才能证明监控不是永远绿灯。', sourceIds: ['clipGrad'] },
        { heading: '05 这段代码不替代真实 VLA 训练配置', body: '脚本以一个 Linear 层、CPU 和人工常量数据测试 API 契约，不包含梯度累积、AMP、DDP/FSDP 或多参数组。它能证明顺序、计数和裁剪行为，却不能给出 SmolVLA、π0 或 SO-101 的最优 max_norm。\n\n接入真实项目时，应把 max_norm、每组 lr、warmup_updates、有效 batch size 和 scheduler 总步数都写入配置快照；日志保存裁剪前范数与触发标志。这样异常发生时才能重放同一 batch，而不是凭印象改超参数。' },
      ],
      points: ['clip_grad_norm_ 返回裁剪前总范数，并原地改梯度。', '裁剪在 optimizer.step 前，scheduler.step 在成功更新后。', 'NaN/Inf 应明确失败，不能用裁剪掩盖。'],
      codeTitle: 'guarded_train_step.py · 原创 warmup、裁剪与非有限负例',
      code: ['import torch', '', 'torch.manual_seed(0)', 'model = torch.nn.Linear(1, 1, bias=False)', 'opt = torch.optim.SGD(model.parameters(), lr=0.3)', 'warmup = torch.optim.lr_scheduler.LinearLR(opt, start_factor=1/3, end_factor=1.0, total_iters=2)', 'assert abs(opt.param_groups[0]["lr"] - 0.1) < 1e-9', '', 'opt.zero_grad(set_to_none=True)', 'loss = (model(torch.tensor([[10.0]])) - torch.tensor([[100.0]])).square().mean()', 'loss.backward()', 'pre = torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0, error_if_nonfinite=True)', 'post = torch.sqrt(sum(p.grad.square().sum() for p in model.parameters()))', 'assert pre > 1.0 and post <= 1.000001', 'opt.step()', 'warmup.step()', 'assert abs(warmup.get_last_lr()[0] - 0.2) < 1e-9', '', 'p = torch.nn.Parameter(torch.tensor(1.0))', 'p.grad = torch.tensor(float("nan"))', 'try:', '    torch.nn.utils.clip_grad_norm_([p], 1.0, error_if_nonfinite=True)', 'except RuntimeError:', '    pass', 'else:', '    raise AssertionError("non-finite gradient gate did not fail")', 'print("clip, warmup order, and NaN negative test: PASS")'].join('\n'),
      codeNotes: ['LinearLR 初始化后首个实际更新使用 base_lr×1/3=0.1；第一次 scheduler.step 后变为 0.2。', 'pre 是裁剪前总范数，post 从已被原地修改的梯度重新计算。', 'NaN 负例只验证门禁行为；真实排查还要回溯输入、loss 与 AMP scale。'],
      exercise: { prompt: '把脚本改成累积两个 micro-batch 后才更新一次，并保持 warmup 按参数更新而非 micro-batch 计数。', steps: ['只在循环开始前 zero_grad，两个 loss 分别除以 2 后 backward。', '累积结束后做一次有限性检查与裁剪。', '只调用一次 optimizer.step 和 scheduler.step，并断言 lr 只前进一步。'], solution: '两个 micro-batch 的 loss 各除以 accumulation_steps=2，再连续 backward；第二次后调用 clip、optimizer.step、scheduler.step。初始 lr=0.1，唯一一次调度后应为 0.2，而不是因为两个 micro-batch 前进到 0.3。' },
      quiz: { question: '为什么把 clip_grad_norm_ 放到 optimizer.step 之后是无效护栏？', hint: '说明 optimizer 消费了哪个时刻的梯度。', keywords: ['裁剪', 'optimizer.step', '原地', '梯度', '顺序'], reference: 'optimizer.step 已用当前 .grad 计算并写入参数；之后的 clip 只修改仍留在 .grad 中的数值，无法撤回已经发生的更新。应在 step 前检查有限性并裁剪，再记录返回的裁剪前总范数。' },
      sources: [s.optimizationTutorial, s.linearLR, s.clipGrad, s.adamwDocs],
    },
    insight: {
      title: '稳定训练与快速迭代的取舍：用更新证据保护个人 VLA 预算', minutes: 27,
      prerequisites: '已能实现带 warmup、梯度裁剪和非有限门禁的单次更新，并能读取参数组学习率。',
      connection: '代码课保证训练步按预期执行；路线课决定个人 4090/5090 预算下先验证哪些假设，并把 RAW 与 SO-101 工作变成可展示证据。',
      intro: '稳定不等于慢，快速也不等于把学习率拉高。最省预算的策略是先用小实验排除配置错误，再逐级增加数据与训练时长，每一级都有明确停止条件。',
      outcomes: ['设计逐级训练预算而非一次长跑', '用相对更新量与裁剪触发率解释稳定性', '为 backbone/head/RAW adapter 制定可审计参数组'],
      sections: [
        { heading: '01 先证明能过拟合极小样本，再谈大规模训练', body: '用 1—4 个离线 batch 做短时 overfit：数据、mask、loss 和梯度都正确时，足够容量的模型应显著降低训练误差。若极小样本都学不会，先查契约、冻结、学习率和 loss；继续租整晚 GPU 只会放大未知变量。\n\n极小样本通过仍不表示泛化，只是“管线可学习”证据。第二级才扩大到固定小切分比较参数组和 schedule，第三级再跑完整离线数据；每一级保存配置、样本 ID、初始权重和停止原因。' },
        { heading: '02 用相对更新量观察每个参数组', body: '定义组 g 的相对更新 u_g=||Δθ_g||₂/(||θ_g||₂+ε)。它把不同参数规模放到可比较比例上；若预训练视觉骨干 u_g 长期比新 head 大很多，可能遗忘过快。反过来 u_g≈0 可能是 lr 太小，也可能是梯度没到，需结合昨日的梯度覆盖率判断。\n\n数值例：backbone 参数范数 200、一步更新范数 0.02，则 u=10^-4；head 参数范数 2、更新 0.01，则 u=5×10^-3，后者相对变化是前者 50 倍。这是监控尺度，不是通用安全阈值。', formulas: [{ latex: 'u_g=\\frac{\\lVert\\Delta\\theta_g\\rVert_2}{\\lVert\\theta_g\\rVert_2+\\varepsilon}', explanation: 'u_g 是参数组 g 的相对更新量；ε 只防止分母为零，阈值需由同任务的稳定基线与对照确定。' }] },
        { heading: '03 裁剪触发率能区分偶发尖峰与长期过载', body: '设 N 个成功更新中有 K 次裁剪前总范数超过 C，触发率 ρ=K/N。偶发异常 batch 造成低 ρ 尖峰时，裁剪可限制单步破坏，但仍要回看样本；若 ρ 长期接近 1，说明阈值、loss scale、学习率或数据分布至少一项不匹配，训练实际总在被另一算法重塑。\n\n同时报告裁剪前分位数、触发率和非有限次数，不能只写“启用了 max_norm=1”。阈值从 1 改成 0.1 会改变有效更新大小；如果不记录触发率，就无法知道性能差异来自 base lr 还是长期裁剪。', formulas: [{ latex: '\\rho=\\frac{1}{N}\\sum_{t=1}^{N}\\mathbf{1}[\\lVert g_t\\rVert_2>C]', explanation: 'ρ 是裁剪触发率，N 只统计真正完成反向并准备更新的步；它描述护栏活跃程度，不直接表示模型质量。' }], sourceIds: ['clipGrad'] },
        { heading: '04 VLA 参数组应反映模块新旧与证据强弱', body: '预训练 VLM backbone、随机初始化 action head、状态投影和 RAW adapter 起点不同。首轮可让新 head/adapter 使用较高 lr，backbone 冻结或使用更低 lr；收益是降低语义表示被小数据迅速破坏的风险，代价是模型可能难以适应机器人视觉域。\n\n不要一次同时解冻 backbone、改变 RAW 融合、加长 warmup 又换 optimizer。更有解释力的阶梯是：RGB head-only 基线；固定 backbone 加 RAW adapter；再解冻末层。每级固定数据切分与更新预算，比较普通光照、高动态范围和动作成功代理指标，才能把 RAW 价值与调参影响分开。', sourceIds: ['adamwDocs', 'adamwPaper'] },
        { heading: '05 SO-101 先做离线训练证据，不把自动化当真机许可', body: '个人项目的当日产出可以是一张训练卡：代码提交、数据版本、参数组表、lr 曲线、裁剪统计、最佳离线 checkpoint 与失败原因。它比一张最终 loss 图更能证明你会定位问题，也便于面试中解释为什么选择较低 backbone lr。\n\n本自动化不会发送 SO-101 动作、运行标定或上传客户/合作方数据。以后真机验证还需独立完成限位、急停、速度、工作空间和数据授权审核；optimizer 稳定只说明训练数值，没有授予机械安全或隐私合规。' },
      ],
      points: ['先过拟合极小离线样本，再逐级扩大预算。', '相对更新量和裁剪触发率让“稳定”可审计。', 'VLA 参数组按模块新旧分层，RAW 价值用固定对照证明。'],
      codeTitle: 'group_update_audit.py · 原创参数组相对更新检查',
      code: ['import torch', '', 'backbone = torch.nn.Parameter(torch.tensor(2.0))', 'head = torch.nn.Parameter(torch.tensor(2.0))', 'opt = torch.optim.SGD([', '    {"params": [backbone], "lr": 1e-3, "name": "backbone"},', '    {"params": [head], "lr": 1e-2, "name": "head"},', '])', 'before = {"backbone": backbone.detach().clone(), "head": head.detach().clone()}', 'loss = (backbone + head - 1.0).square()', 'loss.backward()', 'opt.step()', '', 'delta_backbone = (backbone.detach() - before["backbone"]).abs()', 'delta_head = (head.detach() - before["head"]).abs()', 'u_backbone = delta_backbone / before["backbone"].abs()', 'u_head = delta_head / before["head"].abs()', 'assert torch.allclose(delta_head / delta_backbone, torch.tensor(10.0))', 'assert torch.allclose(u_head / u_backbone, torch.tensor(10.0))', 'print("head/backbone relative update ratio=10: PASS")'].join('\n'),
      codeNotes: ['两个标量的初值和梯度相同，故更新差异只来自 10 倍参数组 lr，便于因果核对。', '真实 VLA 中梯度与参数范数都不同，不能假定 u 比值等于 lr 比值。', '脚本只做一次离线数值更新，不加载数据、权重或控制硬件。'],
      exercise: { prompt: '加入一个 RAW adapter 参数组，并设计“冻结 backbone、训练 RAW/head”的断言。', steps: ['把 backbone.requires_grad 设为 False，并从 optimizer 可训组中排除。', '给 RAW 与 head 设置显式 lr 和 name。', '更新后断言 backbone 不变、RAW/head 改变，并打印两组 u_g。'], solution: '保存三组 before；backbone.requires_grad_(False)，optimizer 只接收 raw/head。loss 必须依赖三者，但 backward 后 backbone.grad 应为 None；step 后 backbone 与快照相等，raw/head 的差值均非零。相对更新只在可训组计算。' },
      quiz: { question: '为什么“裁剪触发率长期接近 100%”不能被解释成训练很安全？', hint: '考虑实际执行的更新和被掩盖的根因。', keywords: ['触发率', '梯度裁剪', '阈值', 'loss scale', '数据'], reference: '长期几乎每步裁剪说明未裁剪梯度尺度与阈值持续不匹配，训练实际一直使用被重缩放的方向；这可能来自阈值过低、loss scale/权重错误、异常数据或学习率配置。裁剪限制了单步大小，却可能掩盖根因并改变算法，需结合范数分布、样本与对照诊断。' },
      sources: [s.adamwDocs, s.adamwPaper, s.clipGrad, s.linearLR],
    },
  },
};
