import type { AuthoredDay } from './types';
import { sources as s } from './sources';

export const day13: AuthoredDay = {
  reviewedAt: '2026-09-09', revision: '逐课编写 1.0',
  deliverable: '一张续训状态边界图、一个在内存中验证中断前后逐步等价的 PyTorch 脚本，以及一份适合个人 VLA 项目的实验身份卡与恢复验收表。',
  question: {
    title: '同一 checkpoint 恢复后第一步 loss 相同，第二步开始分叉；怎样判断是 optimizer、RNG、sampler 还是配置造成的？',
    summary: '先固定恢复边界，再逐项比对下一批数据、学习率、动量和随机状态。',
    keywords: ['checkpoint', 'optimizer', 'RNG', 'sampler', '配置快照', '逐步对齐'],
    reference: '在同一软硬件与代码版本下，保留一条不中断的参考轨迹，并在恢复点记录 global_step、下一批 sample ID、optimizer param_groups 与状态张量、scheduler last_epoch/当前学习率、Python/NumPy/PyTorch/CUDA RNG 以及数据 manifest/配置指纹。恢复后在 step 前先比较 batch ID、前向 loss 和梯度，再比较更新后参数。若第一步 loss 同而之后分叉，优先查未恢复的动量/二阶矩、scheduler 相位和第一步后才消耗的 RNG；若 batch ID 已不同，先修 sampler offset，不要用最终 loss 猜根因。',
  },
  lessons: {
    foundation: {
      title: 'Checkpoint 的真正语义：保存一个可继续的训练状态', minutes: 32,
      prerequisites: '已掌握 9 月 9—12 日的 autograd、AdamW/scheduler、AMP 与分项 loss，能区分模型参数、梯度和 optimizer 状态。',
      connection: '昨天定义了 loss 的有效分母与任务权重；今天把这些定义连同训练进度一起冻结成可审计恢复点。明天的 profiler 会在这个稳定基线上测吞吐与等待。',
      intro: '“能加载权重”和“能继续训练”是两个不同命题。前者只要恢复参数与 buffer；后者要恢复会影响下一次更新的全部状态，并声明“等价”只在哪些环境条件下成立。',
      outcomes: ['区分推理权重、可续训 checkpoint 与可重现实验包', '用状态边界解释为什么同 seed 不等于原地续跑', '设计中断轨迹与连续轨迹的对齐检查'],
      sections: [
        { heading: '01 从参数快照扩展到训练状态', body: '模型 state_dict 包含参数和已注册 buffer，适合推理或暖启动；它不包含 AdamW 的 exp_avg/exp_avg_sq、scheduler 相位、GradScaler 的 scale，也不知道数据读到哪里。因此只保存 model.state_dict 后“从上次 step 继续”，实际是在旧权重上重置优化动力学。\n\n一个单机可续训 checkpoint 至少需要 model、optimizer、scheduler、scaler、global_step 与 RNG 状态；数据随机采样还需 sampler/generator 位置或能由 step 精确推导的 offset。配置和数据 manifest 不一定是可变状态，却是解释 checkpoint 的不可缺语境。', sourceIds: ['checkpoint', 'optimizerState'] },
        { heading: '02 恢复是对随机过程的定位，不是再播一次 seed', body: '把 seed 设为 13 只是把随机数生成器放回序列起点。如果中断前已调用了权重初始化、dropout、数据增强和 shuffle，续训时重设 seed 会重播早期随机数，而不是到达中断时的 RNG 内部状态。要跟上原轨迹，应在恢复对象构造完成后最后 set_rng_state。\n\nPyTorch 明确不保证跨版本、跨平台或 CPU/GPU 的完全复现。即使 RNG 一致，非确定算子、不同 attention backend 和浮点累加顺序也可能产生分差。所以“续训等价”要带上同代码、依赖、硬件与确定性设置的前提。', sourceIds: ['randomness'] },
        { heading: '03 用状态前沿衡量 checkpoint 完整性', body: '把第 t 次更新后能决定下一步的集合记为 S_t，训练转移是 S_{t+1}=F(S_t,B_{t+1};E)，其中 B 是下一批数据，E 是环境与代码契约。checkpoint C_t 只要缺了 S_t 中的一项，加载就实现了另一个转移函数。\n\n例如原轨迹 step=1000 时学习率为 10^{-4}、Adam 二阶矩已稳定，而恢复后 scheduler 回到 step=0、二阶矩置零；即使同一 batch 的更新前 loss 相同，更新量也不同。验收要比较下一 batch ID、更新前 loss/梯度与更新后参数，不是只看远处一个最终 loss。', formulas: [{ latex: 'S_{t+1}=F(S_t,B_{t+1};E),\\qquad C_t\\supseteq\\{\\theta_t,o_t,q_t,r_t,d_t\\}', explanation: 'θ 是模型参数/buffer，o 是 optimizer 状态，q 是 scheduler/scaler 相位，r 是 RNG，d 是数据位置；E 另含代码、版本与硬件契约。' }] },
        { heading: '04 可复现不等于逐位相同', body: '调试 checkpoint 时可要求在受控 CPU 示例里逐位一致，这能暴露缺状态和错误顺序。但对真实 GPU VLA，跨机器逐位等价可能不成立；更合理的层级是状态结构对齐、第一步数值容差、若干步轨迹容差和最终指标分布。\n\n确定性往往有性能代价，因此可以分两种模式：调试/回归模式强制 deterministic algorithms 并用小数据验证；正式训练模式记录 backend 与容差，用多 seed 指标衡量稳健性。不能因为“只能近似复现”就放弃保存 RNG 和实验语境。', sourceIds: ['randomness'] },
      ],
      points: ['推理权重、续训状态与实验身份是三个不同层级。', '同 seed 只定位起点，恢复需要 RNG 的当前内部状态。', '验收 checkpoint 要对齐下一批数据与下一次参数更新。'],
      codeTitle: 'rng_frontier.py · 原创 RNG 起点与中断状态正反例',
      code: ['import torch', '', 'torch.manual_seed(13)', 'prefix = torch.randn(4)', 'saved_rng = torch.get_rng_state()', 'expected = torch.randn(4)', '', 'torch.manual_seed(13)', 'wrong = torch.randn(4)', 'assert torch.equal(wrong, prefix)', 'assert not torch.equal(wrong, expected)', '', 'torch.set_rng_state(saved_rng)', 'resumed = torch.randn(4)', 'assert torch.equal(resumed, expected)', '', 'g = torch.Generator().manual_seed(99)', 'g_state = g.get_state()', 'first = torch.rand(3, generator=g)', 'g.set_state(g_state)', 'assert torch.equal(torch.rand(3, generator=g), first)', 'print("RNG frontier restored: PASS")'].join('\n'),
      codeNotes: ['反例重设 seed=13 只会重现 prefix，不会生成中断后的 expected；get/set_rng_state 才恢复消耗位置。', '独立 Generator 的状态也必须单独保存；示例未覆盖 Python、NumPy、CUDA 或多进程 DataLoader。'],
      exercise: { prompt: '为含 dropout、NumPy 增强和 DataLoader generator 的单机训练列出 checkpoint 状态边界。', steps: ['按模型、优化、随机、数据、配置五类列表。', '说明每项应在构造对象前还是后恢复。', '设计一个缺 NumPy state 的负例。'], solution: '应保存 model/optimizer/scheduler/scaler/global_step，Python random、NumPy、torch CPU 及各 CUDA RNG，DataLoader generator/sampler 位置，以及数据 manifest、配置与版本指纹。先以保存配置构造模型、optimizer 和 scheduler，加载对象状态后再恢复 RNG，避免构造过程消耗已恢复的序列。负例用 NumPy 随机翻转/裁剪：其他 state 一致但增强参数不同，下一 batch 输入立即分叉。' },
      quiz: { question: '为什么续训时再次调用 manual_seed(saved_seed) 不等于恢复 torch.get_rng_state() 的结果？', hint: '区分随机序列的起点与当前位置。', keywords: ['manual_seed', 'RNG state', '序列', '消耗位置', '恢复'], reference: 'manual_seed 重建一条序列并把位置放在起点；中断前初始化、dropout、采样等已经消耗若干随机数。get_rng_state 保存的是消耗后的内部状态，set_rng_state 才会让下一次调用对齐原轨迹。' },
      sources: [s.checkpoint, s.randomness, s.optimizerState],
    },
    code: {
      title: '实现断点恢复与配置快照：验证下一次更新', minutes: 38,
      prerequisites: '能搭建最小训练循环，理解 optimizer/scheduler state_dict、global_step 和 RNG 状态。',
      connection: '基础课定义了状态前沿；本课对照 PyTorch 和 LeRobot 真实入口，用断点前后逐步等价测试把它变成可执行契约。',
      intro: '高质量 checkpoint 代码不是一个 torch.save 调用，而是一对 save/resume 协议和一组负例。你要能回答哪些字段是恢复必需、加载顺序为什么如此，以及结构对得上但语义已错时怎么及早失败。',
      outcomes: ['用 BytesIO 实现不落盘的 checkpoint 正例', '解释 Optimizer.state_dict 的 param_groups 顺序契约', '用连续轨迹发现只恢复权重的伪续训'],
      sections: [
        { heading: '01 真实入口先定义构造和恢复顺序', body: 'PyTorch 的 general checkpoint 示例要先构造 model 与 optimizer，再加载各自 state_dict。当有 LRScheduler 时，官方警告更精确：先构造 scheduler，然后加载 optimizer 状态，避免 scheduler 初始化覆盖 checkpoint 里的学习率；之后再加载 scheduler 自身相位。\n\n若使用 AMP，GradScaler 也有会随溢出而改变的 scale/growth tracker；若有 EMA、动态 loss 权重或 replay sampler，它们同样要进入协议。最后恢复 RNG，再取下一 batch，可避免构造对象的随机初始化抢走了 checkpoint 序列。', sourceIds: ['checkpoint', 'optimizerLoadState', 'lrSchedulerState'] },
        { heading: '02 optimizer 的参数 ID 不是稳定业务主键', body: 'Optimizer.state_dict 将状态保存为 state 和 param_groups。实现中 state_dict 的 pack_group 把当前 Parameter 对象映射为顺序索引；load_state_dict 会检查参数组数量和每组长度，然后将保存的 ID 与当前参数按顺序 zip。\n\n这意味着“张量个数一样”不保证语义一样。若重构后参数组顺序改变，状态可能被配到错误参数；尤其同 shape 时不一定立刻报错。保存参数名称清单和配置指纹，加载前先检查顺序，比盲目 strict=False 更安全。', sourceIds: ['optimizerState', 'optimizerSource'] },
        { heading: '03 LeRobot 把数据位置视为恢复的一等状态', body: 'LeRobot 当前 lerobot_train.py 将恢复拆为两段：resume_before_prepare 先恢复 step 与 RNG，make_dataloaders 依据 step、batch size 与数据并行 world size 重建 sampler offset；Accelerate prepare 之后，resume_after_prepare 再恢复分片模型、optimizer 与 scheduler 状态。\n\n源码还明确警告：改变 dp_world_size 或 batch_size 可以在 epoch/offset 意义上跳到近似位置，但要保持每 rank 样本精确一致必须保持并行拓扑。对个人小数据 VLA，记录下一 batch 的 episode/frame ID 是成本很低的恢复证据。', sourceIds: ['lerobotTrainResume'] },
        { heading: '04 原子性、诚信检查与故障注入', body: '真实落盘不应直接覆盖 last.pt：先写同盘临时文件，flush/fsync 后用原子 rename 切换，再更新 latest 指针。另存 schema_version、字节数与哈希，加载时先验证身份，能区分“最后一次训练”和“最佳验证”两种指针。本课 BytesIO 示例只测序列化协议，没有模拟文件系统崩溃。\n\n故障注入至少覆盖三类：删除 optimizer state 应使轨迹比较失败；修改配置指纹应在训练前拒绝；截断 checkpoint 应在完整性检查阶段失败。只测“能 load”会漏掉最危险的静默分叉。', sourceIds: ['serializationSource'] },
      ],
      points: ['恢复顺序是协议的一部分，尤其是 scheduler、optimizer 和 RNG。', 'optimizer state 按参数组顺序绑定，重构后必须验证名称与配置。', '正例要比较连续轨迹，负例要证明缺状态会被检出。'],
      codeTitle: 'exact_resume.py · 原创内存 checkpoint 逐步等价与伪续训负例',
      code: ['import io', 'import torch', '', 'def make():', '    model = torch.nn.Linear(3, 1)', '    opt = torch.optim.AdamW(model.parameters(), lr=0.02)', '    sched = torch.optim.lr_scheduler.StepLR(opt, step_size=2, gamma=0.5)', '    return model, opt, sched', '', 'def step(model, opt, sched):', '    x = torch.randn(4, 3)', '    y = torch.randn(4, 1)', '    opt.zero_grad(set_to_none=True)', '    loss = (model(x) - y).square().mean()', '    loss.backward(); opt.step(); sched.step()', '    return loss.detach()', '', 'torch.manual_seed(13)', 'base_m, base_o, base_s = make()', 'base_losses = [step(base_m, base_o, base_s) for _ in range(6)]', '', 'torch.manual_seed(13)', 'part_m, part_o, part_s = make()', 'part_losses = [step(part_m, part_o, part_s) for _ in range(3)]', 'payload = {"step": 3, "model": part_m.state_dict(), "optimizer": part_o.state_dict(),', '           "scheduler": part_s.state_dict(), "rng": torch.get_rng_state(),', '           "config": {"in": 3, "out": 1, "schedule": "step2x0.5"}}', 'buf = io.BytesIO(); torch.save(payload, buf); buf.seek(0)', 'saved = torch.load(buf, weights_only=True)', '', 'res_m, res_o, res_s = make()', 'res_m.load_state_dict(saved["model"])', 'res_o.load_state_dict(saved["optimizer"])', 'res_s.load_state_dict(saved["scheduler"])', 'torch.set_rng_state(saved["rng"])', 'res_losses = [step(res_m, res_o, res_s) for _ in range(3)]', 'assert all(torch.equal(a, b) for a, b in zip(base_losses[3:], res_losses))', 'assert all(torch.equal(a, b) for a, b in zip(base_m.parameters(), res_m.parameters()))', '', 'bad_m, bad_o, bad_s = make()', 'bad_m.load_state_dict(saved["model"])', 'torch.set_rng_state(saved["rng"])', '[step(bad_m, bad_o, bad_s) for _ in range(3)]', 'assert any(not torch.equal(a, b) for a, b in zip(base_m.parameters(), bad_m.parameters()))', 'print("exact resume passes; weights-only resume diverges: PASS")'].join('\n'),
      codeNotes: ['连续跑 6 步与 3+checkpoint+3 步在受控 CPU 上逐步比较 loss 和最终参数；RNG 在新对象构造后才恢复。', '负例只加载模型和 RNG，AdamW 与 scheduler 重置，因而同数据也会在更新后分叉。', '示例故意不写文件、不含 CUDA/AMP/DataLoader/分布式；生产代码还需原子替换、哈希和 schema 迁移。'],
      exercise: { prompt: '扩展示例，在加载前检查 optimizer 参数名称顺序和配置指纹。', steps: ['构造 optimizer 时保存每组 named_parameters 名称列表。', '对 canonical JSON 计算 SHA-256 并随 checkpoint 保存。', '交换两个同 shape 层的分组顺序，确认加载前拒绝。'], solution: '把影响模型、数据、loss、optimizer 和 scheduler 的配置排序序列化后哈希；把每个 param_group 的语义标签与按顺序的参数名一起保存。resume 先比较 schema、config hash 和名称序列，再调 load_state_dict。对明确允许的变更应写版本化迁移，不使用无条件忽略。' },
      quiz: { question: 'Optimizer.load_state_dict 为什么可能在参数组长度一致时仍静默加载错状态？', hint: '核对源码中保存 ID 与当前 Parameter 的映射方式。', keywords: ['param_groups', '顺序', 'zip', '参数 ID', '语义校验'], reference: '保存的 ID 只是 optimizer 状态与 param_group 的关联键；加载会在检查组数和长度后，把保存 ID 与当前 Parameter 按顺序 zip。若重构后同 shape 参数换了位置，结构检查可通过却把动量绑错对象，因此还要保存并校验名称顺序。' },
      sources: [s.checkpoint, s.optimizerState, s.optimizerLoadState, s.lrSchedulerState, s.optimizerSource, s.serializationSource, s.lerobotTrainResume],
    },
    insight: {
      title: '实验追踪路线：让每个 VLA 结论都能回到数据和代码', minutes: 27,
      prerequisites: '能完整恢复单机训练，并理解配置、数据 manifest、checkpoint 与指标曲线的不同职责。',
      connection: '代码课保证一条训练能接着跑；路线课把它扩展为能比较、能反驳、能向招聘者解释的 SO-101 实验证据链。',
      intro: '实验追踪的目标不是生产更多仪表盘，而是让一个结论可被追问：这条曲线用了哪份数据、哪个代码版本、哪个配置、哪个 checkpoint，中断恢复是否改变了轨迹。',
      outcomes: ['建立不依赖特定云服务的最小实验身份卡', '区分运行可复现、结论可复现与多 seed 稳健性', '按个人算力选择日志频率、checkpoint 节奏和保留策略'],
      sections: [
        { heading: '01 运行 ID 要是身份，不是一个自增数字', body: '最小身份卡应包含 code revision、已冻结配置哈希、数据 manifest 哈希、seed、环境摘要、父 checkpoint ID 和任务语义。run_id 可以是这些字段的短哈希加人可读前缀；如果配置或数据改了，就是新运行，不应继续写进旧曲线。\n\nTensorBoard SummaryWriter 需要明确 log_dir 和 global_step。默认目录包含时间与主机名，方便创建新运行，却不能代替身份卡；add_scalar 保存标量与 step，也不会自动关联 checkpoint 和数据版本。曲线只是证据链的一端。', sourceIds: ['tensorboardDocs', 'tensorboardSource'] },
        { heading: '02 恢复曲线要维持 step 单调与分支语义', body: '断点续训若从 global_step=2000 恢复，新日志的第一个 step 应是 2001；若从早期 checkpoint 尝试新学习率，应创建带 parent_checkpoint 的新 run，而不是把两条轨迹拼成一条看似平滑的曲线。\n\n异步日志可能还在队列中，所以保存 checkpoint 时应记录同一 step 的 commit 事件，关闭前 flush/close。即使如此，指标文件与 checkpoint 仍是两个资源；需要由 run manifest 同时指向它们，才能区分日志丢失、权重丢失和恢复分支。', sourceIds: ['tensorboardSource'] },
        { heading: '03 个人算力下的记录密度要围绕决策', body: '每 step 记录所有参数直方图会放大 IO 与存储成本，也不一定帮助决策。SO-101 小数据 VLA 可以每若干 step 记录分项 loss、学习率、梯度范数和吞吐；每个评测点记录离线动作误差、越界率与固定 episode 可视化。\n\ncheckpoint 可采用 latest+若干周期点+best 的分层保留：latest 供容灾，周期点供轨迹回溯，best 只代表固定验证准则下的候选。若每 500 step 保存、平均每 step 2 秒，故障的最大重算窗口约 1000 秒；这个时间与 checkpoint 写入成本共同决定节奏。', formulas: [{ latex: 'T_{\\mathrm{redo,max}}=K\\,t_{\\mathrm{step}},\\qquad R_{\\mathrm{ckpt}}=\\frac{t_{\\mathrm{save}}}{K\\,t_{\\mathrm{step}}}', explanation: 'K 是保存间隔 step 数，t_step 是平均每 step 时间，t_save 是一次保存耗时；R 是保存时间占训练区间的近似比例。' }] },
        { heading: '04 多 seed 回答稳健性，checkpoint 回答身份', body: '单 seed 的断点逐步一致，证明恢复实现没有明显缺状态；它不证明算法对初始化、数据顺序或标注噪声稳健。多 seed 实验回答后一个问题，应使用相同数据 manifest、评测协议与训练预算，报告均值、离散度和失败种子。\n\n对 RAW 输入适配器或新 action head 的比较，先用同一 seed 做机制调试与 checkpoint 续训回归，再使用预先选定的 seed 集合进行结论比较。不能中途只保留最好 seed，也不能把云端图表当成可复现本身。', sourceIds: ['randomness', 'tensorboardDocs'] },
      ],
      points: ['身份卡将代码、配置、数据、环境与父 checkpoint 连成一个 run。', '日志频率和 checkpoint 节奏应由决策价值、IO 成本与可接受重算窗口决定。', '断点回归和多 seed 实验回答不同问题，两者都不应省略。'],
      codeTitle: 'run_identity.py · 原创配置/数据指纹与分支检查',
      code: ['import hashlib', 'import json', '', 'def digest(obj):', '    raw = json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)', '    return hashlib.sha256(raw.encode()).hexdigest()[:12]', '', 'config = {"model": "tiny-vla", "lr": 3e-4, "loss": {"action": 1.0, "success": 0.1}}', 'data = {"episodes": ["ep01", "ep02"], "split": "train-v1"}', 'identity = {"code": "abc1234", "config": digest(config), "data": digest(data),', '            "seed": 13, "parent": "step-2000"}', 'run_id = "so101-" + digest(identity)', '', 'same = json.loads(json.dumps(config))', 'assert digest(same) == identity["config"]', 'changed = json.loads(json.dumps(config))', 'changed["loss"]["success"] = 0.3', 'assert digest(changed) != identity["config"]', '', 'resume_manifest = {**identity, "global_step": 2000, "next_step": 2001}', 'assert resume_manifest["next_step"] == resume_manifest["global_step"] + 1', 'print(run_id, "identity and branch guard: PASS")'].join('\n'),
      codeNotes: ['sort_keys 和紧凑分隔符把同一 JSON 语义归一化；权重由 0.1 改为 0.3 会产生新配置指纹。', '12 位短哈希只适合人可读 ID，完整 manifest 应保存完整 SHA-256、schema_version 与原始内容；本例不上传数据或日志。'],
      exercise: { prompt: '为“RAW adapter 对 RGB 基线”设计三次 seed 的运行命名、父子关系和保留策略。', steps: ['固定数据 manifest、评测切分和 seed 集合。', '每个方案按 seed 创建独立 run，禁止把曲线合并。', '指定 latest、periodic、best 和失败种子的保留原则。'], solution: '基线与 RAW 方案各用同一预先声明的 seed 集合，run ID 包含方案、seed 和身份短哈希。若 RAW 从基线 checkpoint 微调，manifest 记录确切 parent；若从头训练则 parent 为 null。每个 run 保留 latest 供容灾、固定频率节点供回溯、预定义验证准则下的 best；失败 seed 不删除，至少保留身份卡、关键日志和可复现失败的 checkpoint。' },
      quiz: { question: '为什么 TensorBoard 上有完整 loss 曲线，仍不足以证明一个 VLA 实验可复现？', hint: '曲线记录了什么，又没有记录什么？', keywords: ['TensorBoard', 'global_step', '配置', '数据 manifest', 'checkpoint', '证据链'], reference: 'loss 曲线只是某些 step 的观测值；它不自动冻结代码、配置、数据切分、环境、RNG 和对应 checkpoint，也不证明恢复后没有分叉。需要 run manifest 将这些身份与日志关联，再用断点回归和多 seed 结果分别验证实现完整性与结论稳健性。' },
      sources: [s.randomness, s.tensorboardDocs, s.tensorboardSource, s.lerobotTrainResume],
    },
  },
};
