import type { AuthoredDay } from './types';
import { sources as s } from './sources';

export const day02: AuthoredDay = {
  reviewedAt: '2026-09-03', revision: '课程正文重写 2.0',
  deliverable: '一个按 episode 切分、能组批并在 epoch 边界恢复的最小训练脚本，以及一张训练耗时账单。',
  question: {
    title: '为什么同一个 seed、同一份模型权重，恢复后的第一步 loss 仍可能不同？',
    summary: '给出数据顺序、优化器和随机状态三类原因；说明如何构造“不中断 / 中断恢复”的对照实验。',
    keywords: ['优化器', '顺序', '随机', 'checkpoint', 'epoch', '归一化'],
    reference: 'seed 只设置随机序列的起点，不会自动回到中断时的随机状态。仅保存模型还会丢失 Adam 动量、学习率进度，以及 DataLoader 的抽样位置。先限定同一软件/硬件、CPU、无随机增强、num_workers=0，并在 epoch 边界保存模型、优化器、下一 epoch、随机状态与数据版本；恢复后先核对 batch 样本 ID，再核对第一次前向 loss 和更新后的参数。中途恢复还需恢复 sampler 游标或保存当轮排列，不能声称只存 epoch 就能精确续跑。',
  },
  lessons: {
    foundation: {
      title: 'Dataset 到梯度更新：一条机器人示教如何变成训练样本', minutes: 30,
      prerequisites: '理解 observation 是模型输入、action 是监督目标；知道张量可以用 shape 表达维度。',
      connection: '昨天区分了 BC 目标与 ACT 架构。今天先搭起能正确供给数据的训练流水线，明天才进入 Transformer 内部。',
      intro: '机器人数据不是一堆可随意打散的图片。一次抓取包含连续状态、图像与控制命令；样本定义一旦错了，网络可以稳定地学会错误关系。我们从一条 100 帧演示出发，逐步说明索引、组批、监督和更新分别做了什么。',
      outcomes: ['写出单样本和 batch 的形状，并区分 batch 维与时间维', '推导带 padding mask 的动作回归损失', '解释为什么评测切分必须先于归一化统计'],
      sections: [
        { heading: '01 样本不是一帧图片，而是一个带时间语义的监督问题', body: '设一次 episode 有 T 帧，时刻 t 的图像为 I_t，关节状态为 q_t。最简单的 BC 用 (I_t,q_t) 预测示教动作 a_t；预测动作块时，目标变成从 t 开始的 K 个动作。这里的 t 不是文件排序号的随意代称：图像曝光时刻与控制命令时刻必须匹配。你熟悉传感器时间同步，可以把这看作“测量值—采样时刻—执行时刻”的关联问题。\n\n例如 T=100、K=8、t=97，只剩 3 个真实动作。不能越过 episode 边界去拼接下一次抓取开头，也不能将补齐的 5 个零动作当成专家主动选择的静止。样本应同时返回动作块和长度为 K 的有效位，后面的损失用它区分事实与占位。', sourceIds: ['actdata'] },
        { heading: '02 Dataset、Sampler 与 DataLoader 各自承担什么', body: 'Dataset 定义“给我索引 i，返回哪一条样本”，通常需要实现 __len__ 和 __getitem__。Sampler 决定先访问哪些索引，例如随机排列或按权重抽样；DataLoader 负责取出多条样本、组批及可选的并行读取。把这三个职责分开，可以独立测试样本语义、采样分布和吞吐。\n\n假设单样本的图像 shape 为 [2,3,224,224]，分别表示两路相机、RGB、高和宽；动作块为 [8,6]。批量大小 B=4 后得到 [4,2,3,224,224] 和 [4,8,6]。最前面的 4 是独立样本数，8 才是时间长度；把两者混淆会让注意力或 loss 沿错误的轴聚合。', sourceIds: ['data'] },
        { heading: '03 从平方误差推导有效动作的平均损失', body: '模型输出与专家动作都应先使用训练集统计做相同的尺度处理。不同关节的数值尺度相差很大时，未经归一化的平方误差会让大尺度关节支配训练。设误差张量为 [B,K,D]，先逐元素平方，再去掉无效时间步，最后除以真正参与监督的标量个数。\n\n以 B=2、K=3、D=2 为例，第一条样本有 3 个有效动作，第二条只有 1 个，分母应是 (3+1)×2=8，而不是 12。如果平方误差有效部分之和为 4，正确均值是 0.5；按完整 tensor 大小平均则得到 0.333，短轨迹多的 batch 会被悄悄降低权重。', formulas: [{ latex: '\\mathcal L=\\frac{\\sum_{b=1}^{B}\\sum_{k=1}^{K}m_{bk}\\sum_{d=1}^{D}(\\hat a_{bkd}-a_{bkd})^2}{D\\sum_{b,k}m_{bk}}', explanation: 'm 为有效位，真实动作取 1，padding 取 0；D 是动作维数。分母为零时应拒绝该 batch，不要用一个常数掩盖全空样本。' }] },
        { heading: '04 一个训练 step 的因果顺序', body: '前向计算产生预测，loss 将预测与目标比较，backward 用链式法则求参数梯度，optimizer.step 再使用梯度更新参数。这四件事不可混为一谈：loss 下降是结果，梯度才是更新依据。PyTorch 默认会累积梯度，因此普通单步训练要先清零；只有明确设计了梯度累积时才跨 batch 保留。\n\n最小排障方法是只取一个固定小 batch 反复训练，观察能否把它过拟合。若连这都做不到，先检查目标与预测 shape、参数是否在优化器中、是否误用了 detach，以及动作 mask 是否全为零。此时贸然采集更多数据，往往只是扩大一个错误监督问题。', formulas: [{ latex: '\\theta_{n+1}=\\theta_n-\\eta\\nabla_\\theta\\mathcal L_{\\mathcal B_n}(\\theta_n)', explanation: '这是 SGD 的基本形式；n 是优化步数，η 为学习率。Adam 会对梯度引入动量和二阶统计，不能把它的恢复状态简化为 θ。' }] },
        { heading: '05 按 episode 切分，再统计归一化参数', body: '同一次示教的相邻帧几乎相同。若先随机打散所有帧再切 train/eval，验证集可能只是训练轨迹的相邻画面，评测会奖励记忆而不是泛化。先按 episode 分组；如果目标是新物体或新摆放，还需要按物体或场景进一步隔离。这是评测问题的定义，不只是数据加载的小选项。\n\n然后仅从训练集计算均值和标准差，把统计与数据版本一同保存。验证和部署必须复用这些统计，不能在各自数据上重新拟合。你可以把“均值变化”看作坐标系变化：同一物理关节值在不同归一化坐标下变成不同输入，权重没有变，策略实际看到的世界却变了。' },
      ],
      points: ['先定义一条监督样本的时间边界，再追求 DataLoader 速度。', 'padding 不是真实动作；loss 必须按有效元素归一化。', '数据切分、统计和特征顺序都是模型契约的一部分。'],
      codeTitle: 'masked_bc_loss.py · 原创教学最小例子（CPU / PyTorch）',
      code: ['import torch', '', 'pred = torch.ones(2, 3, 2, requires_grad=True)', 'target = torch.zeros_like(pred)', 'valid = torch.tensor([[1, 1, 1], [1, 0, 0]], dtype=torch.bool)', 'assert valid.any()', 'error = (pred - target).square()', 'loss = (error * valid[..., None]).sum() / (valid.sum() * pred.shape[-1])', 'loss.backward()', 'assert loss.item() == 1.0', 'assert pred.grad[1, 1:].abs().sum().item() == 0', 'print("loss=1.0; padded gradients=0")'].join('\n'),
      codeNotes: ['valid[..., None] 从 [B,K] 扩成 [B,K,1]，广播到每个动作维。', '最后一条断言验证 padding 的梯度确实为零，而不只是 loss 数字看起来合理。'],
      exercise: { prompt: '把第二条样本的三个动作全部改为无效，但保留第一条样本。', steps: ['先手算分母和 loss。', '运行后检查第二条样本的所有梯度。', '再把整个 batch 都设为无效，解释为什么应报错。'], solution: '分母变成 3×2=6；有效位置的预测仍全为 1，loss 仍是 1。第二条样本梯度全零。全空 batch 没有监督信息，均值无定义，应由断言拒绝。' },
      quiz: { question: '两条 [3,2] 动作块的有效长度为 3 和 1，所有有效标量误差均为 2。损失是多少？为什么不能把补齐动作也计入均值？', hint: '先平方，再数有效标量；解释 padding 的物理含义。', keywords: ['4', '8', 'padding', '有效', '梯度'], reference: '有效标量共 (3+1)×2=8 个，平方误差之和为 8×4=32，均值是 4。补齐动作不是实际示教，若算入会让模型学习不存在的目标；即使把其误差置零后仍除以 12，也会错误缩小损失。' },
      sources: [s.data, s.actdata],
    },
    code: {
      title: '可复现 batch 与 checkpoint：保存的不只是权重', minutes: 35,
      prerequisites: '已理解 Dataset 取样、batch 组装、optimizer.step；知道 epoch 是遍历一次训练集。',
      connection: '基础课定义了正确样本。这一节把“正确”延伸到中断恢复：同一实验不能因为重启就悄悄改变训练轨迹。',
      intro: '云 GPU 到期或训练进程退出后，加载权重并不等于恢复实验。下面用一个没有相机和机械臂的线性回归，隔离抽样顺序与优化器状态，给出可以直接运行的断点恢复检查。',
      outcomes: ['区分推理权重与可续训 checkpoint', '说明 epoch 边界恢复和 batch 中途恢复的不同保证', '用不中断训练作为恢复正确性的测试基准'],
      sections: [
        { heading: '01 先定义你说的“可复现”是哪一级', body: '同一任务的成功率接近、同一环境下 loss 曲线接近、每一步参数逐位相同，是三个强度不同的承诺。本课只对一个受控 CPU 玩具实验要求参数一致：没有随机增强、没有 Dropout、单进程取样、固定张量输入。这个结论不能直接推广到 CUDA、MPS、不同 PyTorch 版本或多 worker 管线。\n\n工程上先保存版本、配置、数据 manifest 和样本顺序，再考虑数值确定性。若恢复后第一个 batch 的样本 ID 都不一样，就没有必要先争论浮点误差。对你租用 GPU 的场景，这能把“换机器后训练变差”的原因拆成环境差异和恢复遗漏两类。', sourceIds: ['randomness'] },
        { heading: '02 优化器为什么也有记忆', body: 'SGD 带动量或 Adam 都不只依赖当前梯度。Adam 的一阶统计积累梯度方向，二阶统计估计梯度幅度；即使加载完全相同的权重，如果把这些统计重置，下一步更新通常也不同。学习率调度器的进度同样影响更新尺度。\n\n因此用于继续训练的快照至少包含模型参数、优化器状态、全局步数、下一 epoch 和配置。若启用了混合精度或 scheduler，还要保存 GradScaler 和 scheduler 状态。本课没使用这两者，不是说它们不重要，而是为了让第一次续训验证只包含两种可控状态。', formulas: [{ latex: 'm_n=\\beta_1m_{n-1}+(1-\\beta_1)g_n,\\qquad v_n=\\beta_2v_{n-1}+(1-\\beta_2)g_n^2', explanation: 'g_n 是当前梯度，m_n、v_n 是 Adam 的状态。只保存权重会遗失式子右侧的历史项。这里省略偏差修正与最终更新式，重点是状态依赖。' }], sourceIds: ['checkpoint'] },
        { heading: '03 固定种子不等于保存随机流的位置', body: '把随机数生成器想成一本确定内容的号码簿：seed 选择哪本簿，RNG state 记录读到哪一页。训练中采样、增强或 Dropout 都可能翻页；恢复时只重新设置同一个 seed，相当于回到第一页。若不同操作共享随机流，增加一次调试采样甚至会改变后续 batch 顺序。\n\n下面刻意用独立 Generator，并让每个 epoch 的排列只由 seed+epoch 决定。这样在 epoch 边界恢复时无需知道前一轮翻了多少页。但若第 3 个 batch 后中断，仍要保存当前排列和游标，或设计可重复跳过机制；不能仅把 epoch 加一，否则会漏掉半轮训练数据。' },
        { heading: '04 读 checkpoint 代码时逐项核对消费者', body: '不要看到一个字典就认为恢复完整。model.load_state_dict 的消费者是模型，optimizer.load_state_dict 的消费者是优化器；epoch 需要被训练循环真正采用，数据版本需要与当前文件核对。一个被保存但从未被读取的字段，没有恢复价值。\n\n下方用 deepcopy 模拟快照，再构建全新模型和优化器，确保不是继续使用内存中的旧对象。所有对照从同一个 init 开始：A 连续跑两轮，B 跑一轮后重建并恢复再跑一轮。比较最终 state_dict 可以抓到漏恢复动量、重跑 epoch、抽样种子变化等错误。真实文件应使用自己生成且可信的 checkpoint，不加载来历不明的序列化对象。' },
        { heading: '05 从这个测试迁移到机器人训练', body: '真实机器人样本通常还有视频解码、相机顺序、归一化统计和动作维映射。它们不一定属于模型的 state_dict，却会改变输入输出。建议额外保存 camera_names、action_names、stats 文件摘要和 train/eval episode ID；部署前逐项匹配，不要靠数组长度恰好相等就认为兼容。\n\n把验收分两层：第一层用本课实验验证恢复机制，第二层在真实数据上记录恢复前后第一批 ID、loss 和学习率。如果第二层失败而第一层通过，优先检查数据 worker、随机增强和 sampler，而不是重写优化器。这样的分层排查才是从“能训练”到“能维护训练系统”的进步。' },
      ],
      points: ['续训 checkpoint 是状态快照，推理权重只是其中一部分。', '本例仅保证固定 CPU 环境下的 epoch 边界恢复。', '恢复测试必须重建对象，并与不中断实验比较。'],
      codeTitle: 'resume_check.py · 原创可运行教学脚本',
      code: ['import copy', 'import torch', '', 'torch.manual_seed(7)', 'x = torch.arange(24, dtype=torch.float32).reshape(12, 2) / 24', 'y = x.sum(dim=1, keepdim=True)', 'init = copy.deepcopy(torch.nn.Linear(2, 1).state_dict())', '', 'def make():', '    model = torch.nn.Linear(2, 1)', '    model.load_state_dict(init)', '    return model, torch.optim.Adam(model.parameters(), lr=0.01)', '', 'def epoch(model, opt, e):', '    g = torch.Generator().manual_seed(100 + e)', '    for ids in torch.randperm(len(x), generator=g).split(4):', '        opt.zero_grad(set_to_none=True)', '        loss = (model(x[ids]) - y[ids]).square().mean()', '        loss.backward()', '        opt.step()', '', 'a, oa = make()', 'epoch(a, oa, 0)', 'epoch(a, oa, 1)', 'b, ob = make()', 'epoch(b, ob, 0)', 'saved = copy.deepcopy({"model": b.state_dict(), "opt": ob.state_dict(), "next_epoch": 1})', 'c, oc = make()', 'c.load_state_dict(saved["model"])', 'oc.load_state_dict(saved["opt"])', 'epoch(c, oc, saved["next_epoch"])', 'assert all(torch.equal(a.state_dict()[k], v) for k, v in c.state_dict().items())', 'print("epoch-boundary resume: PASS")'].join('\n'),
      codeNotes: ['make 总是加载相同 init；否则对照实验的起点不同。', 'epoch 使用独立 Generator；shuffle 不受其他随机操作的影响。', '删除 oc.load_state_dict 后再跑，测试应失败：这是有意的负例。', '磁盘持久化可用 torch.save(saved, path) 与 torch.load(path, weights_only=True)；只处理可信文件。'],
      exercise: { prompt: '分别删除恢复优化器、把 next_epoch 改为 0，预测哪一项状态先出现差异。', steps: ['删除优化器恢复前先保留一份脚本。', '记录下一步 loss 与更新后参数，区分前向一致和更新一致。', '把 batch 索引打印出来，定位 epoch 错误。'], solution: '仅缺优化器状态时，恢复后第一步的前向可以相同，但更新后的参数不同；重跑 epoch=0 会改变 batch 排列，第一步输入和 loss 就可能不同。' },
      quiz: { question: '为什么恢复后第一次 forward 的 loss 相同，optimizer.step 后参数却不同？', hint: '从参数以外的训练状态找原因，不要只回答随机性。', keywords: ['优化器', '动量', '学习率', '状态', 'Adam'], reference: '相同输入与参数可以得到相同前向和梯度，但更新还依赖 Adam 动量/二阶统计、step 计数和学习率。核对 optimizer、scheduler、GradScaler（如启用）的保存与恢复，并用更新后的参数作为验收对象。' },
      sources: [s.checkpoint, s.randomness],
    },
    insight: {
      title: '训练基础设施的价值：把一天变成更多次可信实验', minutes: 25,
      prerequisites: '能解释训练 batch、验证切分和续训快照。',
      connection: '不是把“工程很重要”重复一遍，而是算清你的云 GPU 与每天一小时学习时间被什么消耗。',
      intro: '选更大的 VLA 之前，先问一个更可执行的问题：同样一个晚上，能完成几次值得相信的对照实验？本课用明确的耗时模型、数据泄漏反例和成本账单，把基础设施选择变成可计算的决策。',
      outcomes: ['计算加载和计算的不同重叠方式对 step 时间的影响', '把实验吞吐与可信度共同纳入预算', '为 SO-101 小项目设计先诊断后扩容的顺序'],
      sections: [
        { heading: '01 一步训练不只包含 GPU 计算', body: '串行管线需要先解码视频、读取状态、组批、传输，再运行前向与反向；这时各段时间相加。若数据预取与 GPU 计算真正重叠，稳态吞吐近似由较慢的一段决定。注意这是理想近似：磁盘争用、CPU 饱和和显存复制会破坏完全重叠，不能只看理论式子便宣称提速。\n\n教学例子：加载 80 ms，计算 40 ms，完全串行是 120 ms；理想重叠后是 80 ms。再把 GPU 计算优化到 20 ms，重叠系统仍接近 80 ms。因此 GPU 看起来闲并不一定是模型太小，也可能是视频解码没有喂饱它。你已有图像处理背景，这通常是更有把握的优化入口。', formulas: [{ latex: 'T_{\\rm serial}=T_{\\rm data}+T_{\\rm compute},\\qquad T_{\\rm overlap}\\approx\\max(T_{\\rm data},T_{\\rm compute})', explanation: '两式分别描述无重叠和理想稳态流水线；不包含启动、验证与存盘开销。数字是教学假设，不是某 GPU 的实测基准。' }] },
        { heading: '02 公平比较必须锁住实验的输入', body: '假设你把模型 A 换成 B，同时升级解码器、改了图像裁剪并重新随机切分 episode，成功率提高不能单独归因于 B。把可复现基础设施先固定下来，就能让后续实验每次只改一个值得研究的变量。它的直接收益不一定是更高分数，而是知道为什么分数变了。\n\n机器人项目尤其需要保留失败轨迹。若每次只把成功示教放入训练，评测又来自同一批桌面摆放，你会得到非常顺眼的离线曲线。训练日志、数据 manifest 和固定测试任务共同组成对照的边界；缺少任何一项，换模型的收益都可能与采样偏差混在一起。' },
        { heading: '03 小批量实验也要计算有效产出', body: '设一晚可用 180 分钟，每次配置准备 20 分钟、训练 50 分钟、评测 20 分钟，你只能完成 2 次实验。如果脚本化让准备缩到 5 分钟，缓存让训练缩到 35 分钟，评测仍要 20 分钟，则可完成 3 次。但如果第三次没有记录配置或错用了验证统计，这一次不能计为可信产出。\n\n因此用“可信实验数”而不是单纯 steps/s 衡量迭代。对于你每天 1—2 小时的学习预算，优先让任务能暂停、恢复、追溯，往往比整夜无人值守地训练一个无法解释的模型更有学习收益。这是针对个人项目的决策建议，不是论文已经证明的普遍性能定律。', formulas: [{ latex: 'N_{\\rm valid}=\\left\\lfloor\\frac{T_{\\rm budget}}{T_{\\rm setup}+T_{\\rm train}+T_{\\rm eval}}\\right\\rfloor\\cdot p_{\\rm auditable}', explanation: 'p_auditable 表示实验可追溯、可用于结论的比例。它是管理估计量，不是模型成功率；不要为了让 N 好看而省略评测。' }] },
        { heading: '04 从开源配方借用组织方式，不照抄性能结论', body: 'LeRobot 提供从遥操作到采集、训练、评测的统一流程，可以作为项目骨架；ACT 的数据读取实现能帮助你检查 episode 内动作切片。它们的价值在于暴露了可检查的接口，而不是保证任何相机、任何数据都会得到相同结果。阅读时要记录项目版本与实际使用的配置。\n\n今天可以先借用“同一配置贯穿数据和模型”的组织方式，明天再读策略内部。对尚未装好的机械臂，先使用小型离线样本验证数据契约；没有真机指标时明确标为离线测试。不要把训练 loss 的降低写成 SO-101 成功率提升，也不要将开源团队的演示视频当成你自己的结果。', sourceIds: ['robotil', 'actdata'] },
        { heading: '05 给你的项目安排三步投入顺序', body: '第一步记录一次短训练中每段耗时和数据 ID，发现瓶颈；第二步只优化最慢的那一段，同时验证前后样本与监督没有变；第三步才扩展模型或数据规模。若瓶颈是解码，尝试缓存或调整 worker；若显存不足，先确认 batch、图像尺寸与动作长度，再考虑租更贵设备。\n\n停止条件也要具体：如果耗时优化前后 loss 输入不一致、episode 切分发生变化或回放时间轴错位，就暂停性能比较并修复语义。最终作品可以展示一张前后对照账单：加载时间、计算时间、验证时间、恢复是否通过。这个证据比只写“熟悉训练优化”更可检验。' },
      ],
      points: ['先测数据与计算各自耗时，再决定优化 GPU 还是输入管线。', '更快但无法复现的实验，不应计入有效迭代。', '开源配方是可检查的起点，不是你项目成功率的担保。'],
      codeTitle: 'iteration_budget.py · 原创预算算例',
      code: ['from math import floor', '', 'def experiments(budget, setup, train, evaluate):', '    return floor(budget / (setup + train + evaluate))', '', 'assert experiments(180, 20, 50, 20) == 2', 'assert experiments(180, 5, 35, 20) == 3', 'serial_ms = 80 + 40', 'ideal_overlap_ms = max(80, 40)', 'print(serial_ms, ideal_overlap_ms)  # 120, 80'].join('\n'),
      codeNotes: ['成本模型只给出上界式规划；训练失败、排队和人工复盘还会占时间。', '修改 evaluate 为 0 虽可提高次数，却破坏了“可信实验”的定义。'],
      exercise: { prompt: '用你实际的一次短实验填一张耗时账单，选定一个优化变量。', steps: ['区分首次启动耗时与稳定后的每步耗时。', 'GPU 测时需同步或用事件，不能只测 CPU 提交速度。', '记录优化前后的 batch ID、输入摘要和 loss，确认任务没有被换掉。'], solution: '没有统一目标数字。合格产出应包含真实测量方法、瓶颈证据和语义未变的检查；不能用本页的教学数字充当自己的实测。' },
      quiz: { question: '数据加载 80 ms、计算 40 ms，已理想重叠。把计算加速两倍，step 能否从 80 ms 降为 40 ms？', hint: '先确定哪个阶段是吞吐瓶颈。', keywords: ['80', '加载', '瓶颈', '重叠', 'max'], reference: '不能。计算变为 20 ms，max(80,20) 仍为 80 ms。应测量并优化加载阶段；只有确认预取和计算确实重叠，才可以使用这个近似。' },
      sources: [s.robotil, s.actdata, s.checkpoint],
    },
  },
};
